import { describe, it, expect } from 'vitest'
import { parseAssStyles, pickPrimaryStyle, toSubtitleStyle, captureFromExtradata } from './ass-style-capture'

// Shaped like real muxed-fansub extradata: full Script Info + V4+ header, a dialogue style and
// sign/typesetting styles, ASS &HAABBGGRR colours.
const SUBSPLEASE = `[Script Info]
; Script generated by Aegisub
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Roboto Medium,78,&H00FFFFFF,&H000000FF,&H00201213,&H00000000,0,0,0,0,100,100,0,0,1,3.9,0,2,60,60,69,1
Style: Sign,Verdana,60,&H00FF8040,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,8,10,10,10,1
`

const LEGACY = `[Script Info]
PlayResY: 480

[V4 Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding
Style: OP,Arial,24,&HFFFFFF,&HFF0000,&H000000,&H000000,0,0,1,2,1,2,20,20,20,0,1
`

describe('parseAssStyles', () => {
  it('reads PlayResY and every style with its fields', () => {
    const parsed = parseAssStyles(SUBSPLEASE)!
    expect(parsed.playResY).toBe(1080)
    expect(parsed.styles.map((s) => s.name)).toEqual(['Default', 'Sign'])
    const def = parsed.styles[0]
    expect(def.fontname).toBe('Roboto Medium')
    expect(def.fontsize).toBe(78)
    expect(def.primaryColour).toBe('&H00FFFFFF')
    expect(def.outlineColour).toBe('&H00201213')
    expect(def.outline).toBe(3.9)
    expect(def.shadow).toBe(0)
    expect(def.alignment).toBe(2)
    expect(def.marginV).toBe(69)
  })

  it('handles the legacy [V4 Styles] header', () => {
    const parsed = parseAssStyles(LEGACY)!
    expect(parsed.playResY).toBe(480)
    expect(parsed.styles[0].name).toBe('OP')
    expect(parsed.styles[0].outline).toBe(2)
  })

  it('returns null for empty or non-ASS input', () => {
    expect(parseAssStyles('')).toBeNull()
    expect(parseAssStyles('WEBVTT\n\n00:00.000 --> 00:01.000\nhi')).toBeNull()
  })
})

describe('pickPrimaryStyle', () => {
  it('prefers the style named Default, case-insensitively', () => {
    const styles = parseAssStyles(SUBSPLEASE)!.styles
    expect(pickPrimaryStyle([...styles].reverse())?.name).toBe('Default')
  })
  it('falls back to the first style when no Default exists', () => {
    expect(pickPrimaryStyle(parseAssStyles(LEGACY)!.styles)?.name).toBe('OP')
  })
  it('is null for an empty list', () => {
    expect(pickPrimaryStyle([])).toBeNull()
  })
})

describe('toSubtitleStyle', () => {
  const def = parseAssStyles(SUBSPLEASE)!.styles[0]

  it('maps font name and scales sizes from PlayResY to mpv 720-line space', () => {
    const style = toSubtitleStyle(def, 1080)
    expect(style.font).toBe('Roboto Medium')
    expect(style.fontSize).toBe(52) // 78 * 720/1080
    expect(style.borderSize).toBe(2.6) // 3.9 * 720/1080, rounded to slider step
    expect(style.shadow).toBe(0)
  })

  it('converts ASS &HAABBGGRR colours to #rrggbb (ABGR order, alpha dropped)', () => {
    const style = toSubtitleStyle(def, 1080)
    expect(style.textColor).toBe('#ffffff')
    expect(style.borderColor).toBe('#131220') // &H00201213 → BGR 20 12 13 → RGB 13 12 20
  })

  it('maps a bottom-aligned MarginV into sub-pos and defaults non-bottom styles', () => {
    const style = toSubtitleStyle(def, 1080) // alignment 2 (bottom-center), marginV 69
    expect(style.position).toBe(94) // 100 - 69*(100/1080) = 93.6 → rounded
    const sign = parseAssStyles(SUBSPLEASE)!.styles[1] // alignment 8 (top)
    expect(toSubtitleStyle(sign, 1080).position).toBe(92)
  })

  it('clamps into the settings ranges', () => {
    const huge = { ...def, fontsize: 300, outline: 40, shadow: 40, marginV: 2000 }
    const style = toSubtitleStyle(huge, 1080)
    expect(style.fontSize).toBe(80)
    expect(style.borderSize).toBe(8)
    expect(style.shadow).toBe(8)
    expect(style.position).toBe(10)
  })
})

describe('captureFromExtradata', () => {
  it('goes end to end from extradata to a saveable style', () => {
    const style = captureFromExtradata(SUBSPLEASE)!
    expect(style.font).toBe('Roboto Medium')
    expect(style.fontSize).toBe(52)
  })
  it('is null when there is nothing to capture', () => {
    expect(captureFromExtradata(null)).toBeNull()
    expect(captureFromExtradata('')).toBeNull()
    expect(captureFromExtradata('[Script Info]\nPlayResY: 720\n')).toBeNull()
  })
})
