/** The documented styling hooks theme stylesheets may target (docs/THEMES.md "Styling hooks").
 *  A `slot` is a page region (`data-slot`), a `part` a component (`data-part`). Renaming or
 *  removing one breaks published themes; hooks.test.ts keeps this list and the markup in step.
 *  In markup, write hook names as string literals — `data-part="card"` or
 *  `data-slot={top ? 'nav.top' : 'nav.side'}` — and never put any other quoted string inside a
 *  `data-slot`/`data-part` expression: the test reads every quoted literal there as a hook name. */
export interface ThemeHook {
  name: string
  kind: 'slot' | 'part'
  description: string
  /** State attributes rendered alongside, e.g. `data-active`. */
  states?: string[]
}
export type ThemeHookGroup = 'shell' | 'home' | 'blocks' | 'cards' | 'detail' | 'episodes' | 'watch' | 'pages' | 'primitives'

export const THEME_HOOKS: Partial<Record<ThemeHookGroup, ThemeHook[]>> = {
  shell: [
    { name: 'page', kind: 'slot', description: 'The routed page content (the app <main>).' },
    { name: 'nav.side', kind: 'slot', description: 'The side navigation rail.' },
    { name: 'nav.top', kind: 'slot', description: 'The top navigation bar (shell.nav "top").' },
    { name: 'nav.bottom', kind: 'slot', description: 'The bottom tab bar (phones, or shell.nav "bottom"). `data-state` is the scroll-chrome state (`shown`, `hidden`, `collapsed`), the same as `data-chrome` on <html>. `data-count` and the `--nav-items` custom property are the number of destinations on it, Home included, for sizing a pill to them.', states: ['data-state', 'data-count'] },
    { name: 'nav.item', kind: 'part', description: 'A navigation destination link, or the Categories menu button (`data-variant="menu"`). `data-dest` names the destination on every bar, rail, drawer and panel.', states: ['data-active', 'data-variant', 'data-dest'] },
    { name: 'nav.item.icon', kind: 'part', description: 'The icon of a navigation destination.' },
    { name: 'nav.item.label', kind: 'part', description: 'The label of a navigation destination.' },
    { name: 'search.field', kind: 'part', description: "A search input: the global search overlay, the theme top bar's search field, or the Search page's own field." },
    { name: 'search.suggestions', kind: 'part', description: "The live results panel under the top bar's search field while typing." },
    { name: 'search.suggestion', kind: 'part', description: 'One live result; the keyboard-highlighted one has `data-active`.', states: ['data-active'] },
    { name: 'search.suggestion.poster', kind: 'part', description: "A live result's poster." },
    { name: 'search.suggestion.title', kind: 'part', description: "A live result's title." },
    { name: 'search.suggestion.meta', kind: 'part', description: 'The format, episode count, year and status line of a live result.' },
    { name: 'search.suggestion.all', kind: 'part', description: 'The "View all results" link at the end of the panel.' },
    { name: 'nav.menu', kind: 'part', description: 'The top bar menu button that opens the drawer.' },
    { name: 'nav.bumper', kind: 'part', description: "The L1 or R1 glyph at either end of the top bar's tabs (`shell.top.bumpers`, pad in use).", states: ['data-button'] },
    { name: 'nav.drawer', kind: 'slot', description: 'The side drawer of destinations (top bar `menu: "drawer"`); items are `nav.item`.' },
    { name: 'nav.panel', kind: 'slot', description: 'The pinned menu panel down the left (top bar `menu: "side"`); items are `nav.item`.' },
    { name: 'nav.categories', kind: 'slot', description: 'The Categories menu panel (top bar `categories`).' },
    { name: 'nav.categories.heading', kind: 'part', description: 'The Genres heading in the Categories menu.' },
    { name: 'nav.categories.link', kind: 'part', description: 'A Categories menu link; genre links carry `data-variant="genre"`.', states: ['data-variant'] },
    { name: 'hints.glyph', kind: 'part', description: "A controller button's printed label: round for face buttons, a pill for bumpers, triggers and the menu buttons.", states: ['data-button', 'data-family'] },
    { name: 'hints', kind: 'slot', description: 'The controller button-hint bar along the bottom (`shell.hints`).' },
    { name: 'hints.item', kind: 'part', description: 'One prompt: its glyph (two for the page-tab triggers, `data-button="l2r2"`) and label.', states: ['data-button'] },
    { name: 'hints.label', kind: 'part', description: 'What the button does for the focused element.' },
    { name: 'home.header.action', kind: 'part', description: 'A destination icon in the phone Home app bar (`home.header`), one per destination placed at the top; `data-dest` names it.', states: ['data-dest'] },
    { name: 'home.header.actions', kind: 'part', description: 'The row holding the `home.header.action` icons.' },
  ],
  home: [
    { name: 'home', kind: 'slot', description: 'The Home page.', states: ['data-variant'] },
    { name: 'home.hero', kind: 'slot', description: 'The featured banner on Home. While its titles load, a placeholder with `data-state="loading"` holds its place, with the `data-variant` of the hero that replaces it (`template`, `phone` or `desktop`) and `.skeloader` shimmer inside.', states: ['data-variant', 'data-state'] },
    { name: 'hero.slide', kind: 'part', description: 'The current slide (the artwork layer). During a `fade` transition the outgoing artwork stays under it as a second `hero.slide` with `data-state="leaving"`.', states: ['data-state'] },
    { name: 'hero.art', kind: 'part', description: 'The slide artwork image. On a series page `data-art` names the artwork it shows.', states: ['data-art'] },
    { name: 'hero.scrim', kind: 'part', description: 'A gradient over the artwork.' },
    { name: 'hero.logo', kind: 'part', description: 'The title logo, when the show has one.' },
    { name: 'hero.title', kind: 'part', description: 'The text title, when there is no logo.' },
    { name: 'hero.meta', kind: 'part', description: 'The facts line (format, episodes, score, status).' },
    { name: 'hero.synopsis', kind: 'part', description: 'The description (desktop).' },
    { name: 'hero.actions', kind: 'part', description: 'The Watch, Details and Favorite buttons.' },
    { name: 'hero.indicator', kind: 'part', description: 'The slide marker row.', states: ['data-variant'] },
    { name: 'hero.dot', kind: 'part', description: 'One slide marker.', states: ['data-active', 'data-past'] },
    { name: 'hero.dot.track', kind: 'part', description: 'The drawn shape of a slide marker (its bar, dot or pill).' },
    { name: 'hero.dot.fill', kind: 'part', description: 'The timed fill inside a bar marker (indicator style `bars`).' },
    { name: 'hero.counter', kind: 'part', description: 'The "n / N" counter (indicator style "counter").' },
    { name: 'row', kind: 'slot', description: 'A titled row or grid of cards, on Home and elsewhere. Home rows carry their stable id and role.', states: ['data-row', 'data-role', 'data-layout'] },
    { name: 'row.header', kind: 'part', description: 'The row heading bar.' },
    { name: 'row.title', kind: 'part', description: 'The row title.' },
    { name: 'row.more', kind: 'part', description: "The row's view-more link. Continue Watching has one (to the Library) only when the theme sets `heading.viewMore` on that row itself." },
    { name: 'row.track', kind: 'part', description: 'The scrolling track or grid holding the cards.' },
    { name: 'row.skeleton', kind: 'part', description: 'A placeholder card in a Home row while the row loads (`.skeloader`): posters, or 16:9 cards on Continue Watching.' },
    { name: 'row.caption', kind: 'part', description: 'The focus caption line under a row (`caption: "focus"`, pad in use).' },
    { name: 'row.caption.title', kind: 'part', description: "The focused card's full title in the caption." },
    { name: 'row.caption.meta', kind: 'part', description: "The focused card's detail line: episode, episode title and time left on Continue Watching; format, season and episodes on posters." },
    { name: 'row.empty', kind: 'part', description: 'The empty state inside the Continue Watching track while there is nothing to continue: only with `empty: "shown"` on that row (`rows.byId.continue` or its id); izumi\'s own Home leaves the row out instead.' },
    { name: 'row.empty.text', kind: 'part', description: 'The line of the Continue Watching empty state ("Nothing to continue yet").' },
    { name: 'row.empty.action', kind: 'part', description: 'The Browse link of the Continue Watching empty state (opens Search).' },
  ],
  blocks: [
    { name: 'home.header', kind: 'slot', description: 'The phone Home app bar: the wordmark and the top icons.' },
    { name: 'home.main', kind: 'slot', description: 'The main column of Home; the rows above the side column (`layout.asideStart`) are a second one with `data-variant="lead"`.', states: ['data-variant'] },
    { name: 'home.aside', kind: 'slot', description: 'The side column of Home, holding blocks placed in the aside.' },
    { name: 'pagination', kind: 'part', description: 'Page controls under a block: numbered pages or a Load more button.' },
    { name: 'page-number', kind: 'part', description: 'A page button: a numbered page under a block, Prev/Next under the episode list, or an entry of the episode range picker.', states: ['data-active'] },
    { name: 'block.title', kind: 'part', description: 'A block heading.' },
    { name: 'block.genre-chips', kind: 'slot', description: 'Genre shortcuts: an All chip and one chip per genre (each a `chip`).' },
    { name: 'block.latest-episodes', kind: 'slot', description: 'Newly aired episodes as a grid of stills. Items reuse `episode.still`, `episode.number`, `card.title` and `card.meta`. `data-caption` is `below` or `overlay`.', states: ['data-caption'] },
    { name: 'block.item', kind: 'part', description: 'One entry in a block (an episode, a poster, a ranked title or an airing).', states: ['data-aired'] },
    { name: 'block.tabbed-grid', kind: 'slot', description: 'A tab strip (`tabs`) over a poster grid; each poster is a `block.item` holding a `card`.' },
    { name: 'block.ranked-list', kind: 'slot', description: 'A numbered top list; each entry is a `block.item` with `card.art`, `card.title` and `card.meta`.' },
    { name: 'block.rank', kind: 'part', description: 'The rank number of a ranked-list entry.' },
    { name: 'block.profile-header', kind: 'slot', description: 'The profile banner with the viewer\'s name, watch stats and shortcut buttons (`button`).' },
    { name: 'block.banner', kind: 'part', description: 'The profile banner image.' },
    { name: 'block.profile', kind: 'part', description: 'The avatar, name and stats of a profile header, as one group (hide it to keep only the banner and buttons).' },
    { name: 'block.avatar', kind: 'part', description: 'The profile avatar (an image, or the first letter of the name).' },
    { name: 'block.button.art', kind: 'part', description: "The artwork under a profile-header button's label (`art`): the banner of one of the viewer's own titles." },
    { name: 'block.name', kind: 'part', description: 'The profile name.' },
    { name: 'block.stat', kind: 'part', description: 'One watch statistic, its value then its label: episodes, then titles (`data-key`). izumi shows both on one line; the later one\'s `::before` draws the dot between them.', states: ['data-key'] },
    { name: 'block.stat.value', kind: 'part', description: 'The number of a watch statistic ("26").' },
    { name: 'block.stat.label', kind: 'part', description: 'The word of a watch statistic ("episodes").' },
    { name: 'block.scrim', kind: 'part', description: 'The gradient over the profile banner.' },
    { name: 'block.airing-today', kind: 'slot', description: "Today's airings in time order; each entry is a `block.item` with `airing.poster`, `airing.title` and `airing.time`, and `data-aired` once it has aired." },
    { name: 'block.more', kind: 'part', description: "A block's link to its full page (the schedule, on airing-today)." },
    { name: 'block.clock', kind: 'part', description: 'The date (`block.clock.date`) and live clock (`block.clock.time`) under an airing-today heading.' },
    { name: 'block.clock.date', kind: 'part', description: "Today's date in an airing-today clock." },
    { name: 'block.clock.time', kind: 'part', description: 'The live time in an airing-today clock.' },
    { name: 'airing.poster', kind: 'part', description: 'The poster of an airing-today entry.' },
    { name: 'airing.title', kind: 'part', description: 'The series title of an airing-today entry.' },
    { name: 'airing.time', kind: 'part', description: 'The local airing time of an airing-today entry: a tick once aired, a clock before.' },
  ],
  cards: [
    { name: 'card', kind: 'part', description: 'A media card: poster, search, continue or preview.', states: ['data-family'] },
    { name: 'card.art', kind: 'part', description: 'The card artwork frame.' },
    { name: 'card.title', kind: 'part', description: 'The card title.' },
    { name: 'card.meta', kind: 'part', description: 'The line under the title (season, format, source, episode).' },
    { name: 'card.badge', kind: 'part', description: 'The label on the artwork (for example "Episode 5").' },
    { name: 'card.score', kind: 'part', description: 'The score badge.' },
    { name: 'card.progress', kind: 'part', description: 'The watch-progress track; the fill is its child.' },
    { name: 'card.episode', kind: 'part', description: 'The episode number on resume cards.' },
    { name: 'card.overlay', kind: 'part', description: 'The hover or play overlay on the artwork. A Continue card shows it with `data-state="resolving"` while it looks up its source; over a `continue` template it covers the whole card and exists only then.', states: ['data-state'] },
  ],
  detail: [
    { name: 'detail', kind: 'slot', description: 'The series page. `data-pending` while its record loads: the page is drawn from the card the user tapped, with placeholders (`.skeloader`) inside the parts it cannot fill yet.', states: ['data-layout', 'data-variant', 'data-pending'] },
    { name: 'detail.banner', kind: 'slot', description: 'The artwork area at the top of the series page; `data-art` names the artwork it shows.', states: ['data-art'] },
    { name: 'detail.poster', kind: 'part', description: 'The cover image.' },
    { name: 'detail.column', kind: 'slot', description: 'The left column headed by the poster (`detail.column: "poster"`): the trailer button, the countdown and the facts.' },
    { name: 'detail.trailer', kind: 'part', description: 'The labelled Watch Trailer button in the poster column.' },
    { name: 'detail.title', kind: 'part', description: 'The title.' },
    { name: 'detail.logo', kind: 'part', description: 'The title logo inside `detail.title` (`detail.title: "logo"`).' },
    { name: 'detail.backdrop', kind: 'part', description: 'The header artwork of the series page (the phone band, the backdrop of an overlay page): the banner or key art, or the portrait poster (`detail.art: "portrait"`). On a title with none of them, the cover: shown, sharp, with `detail.artFallback: "cover"`, else hidden behind a wash of its colour until a theme shows it (`data-art="cover"`).', states: ['data-art'] },
    { name: 'detail.body', kind: 'part', description: 'The text column over the artwork of an overlay series page.' },
    { name: 'detail.studio', kind: 'part', description: 'The studio line of the desktop overlay page.' },
    { name: 'detail.rating', kind: 'part', description: 'The "Your rating" row (your score), on every layout once it shows (Settings → Interface). On a phone overlay page it is a `display: contents` box inside the row\'s spacing.' },
    { name: 'detail.rating.label', kind: 'part', description: 'The "Your rating" label of `detail.rating`.' },
    { name: 'detail.rating.value', kind: 'part', description: 'The readout of `detail.rating`: "8/10 · Very Good", or "Not rated".' },
    { name: 'detail.rating.segment', kind: 'part', description: 'One step of `detail.rating` (a bar segment, a star or a number); `data-active` on the steps the score fills (the chosen number in the numbers style).', states: ['data-active'] },
    { name: 'detail.alt-title', kind: 'part', description: 'The native or romaji title.' },
    { name: 'detail.header', kind: 'part', description: 'The theme template under the title (`detail.header`).' },
    { name: 'detail.meta', kind: 'part', description: 'The facts line.' },
    { name: 'detail.facts', kind: 'part', description: 'The facts: a theme template (stacked and split layouts, on phones and desktop) or, with `detail.factsStyle`, a table, cards or chips.', states: ['data-variant'] },
    { name: 'fact', kind: 'part', description: 'One fact: an entry of the details grid, or a table row, card or chip of `detail.facts`.', states: ['data-key'] },
    { name: 'fact.label', kind: 'part', description: 'A details entry label.' },
    { name: 'fact.value', kind: 'part', description: 'A details entry value.' },
    { name: 'detail.genres', kind: 'part', description: 'The genre chips (phone).' },
    { name: 'detail.synopsis', kind: 'part', description: 'The description. `data-expanded` while a phone synopsis shows its whole text.', states: ['data-expanded'] },
    { name: 'detail.actions', kind: 'part', description: 'The action buttons row. With `detail.actions: "expand"` (phones) `data-expanded` while More has unfolded Save, Share and Trailer.', states: ['data-expanded'] },
    { name: 'detail.list-button', kind: 'part', description: 'The tracker list-status button; `data-state="listed"` while the title is on a tracker list.', states: ['data-variant', 'data-action', 'data-state'] },
    { name: 'detail.action', kind: 'part', description: 'A series action that is not a `button`: Trailer, and on phones More (whose menu holds the list button and tracker links).', states: ['data-action'] },
    { name: 'detail.airing', kind: 'part', description: 'The release status of upcoming episodes (sub and dub timing, delays).' },
    { name: 'detail.countdown', kind: 'part', description: 'The next-episode countdown (`detail.countdown`): with the facts, or at the top of the episode list (`countdownAt`).', states: ['data-variant'] },
    { name: 'detail.countdown.label', kind: 'part', description: 'The caption of a `words`, `full` or `date` countdown ("Episode 13 airs in", "Next episode 13").' },
    { name: 'detail.countdown.time', kind: 'part', description: 'The time in a countdown: "2d 21h", "2 days 3 hours", the ticking count or the airing date.' },
    { name: 'detail.episodes', kind: 'slot', description: 'The episode list.' },
    { name: 'detail.relations', kind: 'slot', description: 'Related titles.' },
    { name: 'relation.type', kind: 'part', description: 'The relation above a related title ("sequel", "side story"; "recommended" on a recommendation the Relations section holds).' },
    { name: 'detail.characters', kind: 'slot', description: 'Characters and voice actors.' },
    { name: 'detail.staff', kind: 'slot', description: 'Staff credits.' },
    { name: 'detail.bar', kind: 'slot', description: 'The floating top bar of the phone series page (back, a Home link with `detail.bar.home`, and once scrolled the title).', states: ['data-solid'] },
    { name: 'detail.byline', kind: 'part', description: 'The phone studio · source · members line.' },
    { name: 'person', kind: 'part', description: 'One character or staff credit.' },
    { name: 'person.photo', kind: 'part', description: "The credit's picture." },
    { name: 'person.name', kind: 'part', description: 'The character or staff name.' },
    { name: 'person.role', kind: 'part', description: "The character's role or the staff job." },
    { name: 'detail.heading', kind: 'part', description: 'The heading of the characters ("Characters & Japanese voices") and of the staff.' },
    { name: 'detail.track', kind: 'part', description: 'The grid holding the character credits, the staff credits or the recommended titles; a stylesheet can make it a row.' },
    { name: 'detail.recommended', kind: 'slot', description: 'The recommended titles (also `detail.track`); each title is a `card`.' },
    { name: 'person.voice', kind: 'part', description: "A character's voice actor, a link to their profile when they have one." },
    { name: 'person.voice.photo', kind: 'part', description: "The voice actor's picture." },
    { name: 'person.voice.name', kind: 'part', description: "The voice actor's name." },
    { name: 'person.voice.role', kind: 'part', description: 'The "Japanese voice" label under the voice actor.' },
    { name: 'detail.section', kind: 'slot', description: 'A titled section outside the tab strip: every section with `sections.mode: "stack"`, or a section without a tab inside Overview.', states: ['data-section'] },
    { name: 'detail.section-title', kind: 'part', description: 'The heading of a `detail.section`. On the Episodes section, `data-season-label` names the one season its list shows ("Season 1", "Specials"), when it can be told.', states: ['data-season-label'] },
    { name: 'detail.back', kind: 'part', description: 'The Back button in `detail.bar`.' },
    { name: 'detail.bar.title', kind: 'part', description: 'The series title `detail.bar` shows once the artwork has scrolled under it; with `detail.bar.title: "logo"` it holds the title logo (`detail.bar.logo`) when the title has one.' },
    { name: 'detail.bar.scrim', kind: 'part', description: 'The gradient behind `detail.bar` while it sits over the artwork.' },
    { name: 'detail.buttons', kind: 'part', description: "The phone header buttons in the theme's order (`detail.buttons`): Play, the full-width list button and Download. Only with that key; without it they sit straight in the page's column, as before." },
    { name: 'detail.lead', kind: 'part', description: 'The template at the start of the phone actions row (`detail.actionsLead`), taking its free width.' },
    { name: 'fact.suffix', kind: 'part', description: 'Text after a fact value: " / 10" after a `ten-of` score, " / 26" (or " / ?") after an `aired-of` episode count (`detail.factsFormat`).' },
    { name: 'detail.info', kind: 'part', description: 'The phone Information block (the facts grid of `fact` entries): inside Overview, or a section of its own when `sections.tabs` lists `information`.' },
    { name: 'detail.tags', kind: 'part', description: "The phone Overview's Themes block; every tag is a `chip` (spoiler tags too) with its rank in `data-rank` and a hidden `chip.meta` (\"94%\")." },
    { name: 'detail.synonyms', kind: 'part', description: "The phone Overview's Alternative titles block; each title is a `chip`, inline, every one after the first drawing \" · \" in its `::before` (`content: none` drops it)." },
    { name: 'detail.block-title', kind: 'part', description: 'The heading of a block inside the phone Overview (Synopsis, Information, Themes, Alternative titles).' },
    { name: 'relation', kind: 'part', description: 'One related title (its `relation.type` and its card); `data-relation` is the relation type (`recommended` on a recommendation `sections.relations` adds), `data-media` the kind of title (`anime`, `manga`, `novel`, `one-shot`).', states: ['data-relation', 'data-media'] },
    { name: 'detail.synopsis.more', kind: 'part', description: 'The "more" control after a clamped phone synopsis (`detail.synopsis`); "Show less" while the text is open.' },
    { name: 'detail.content', kind: 'part', description: "The phone page's column under the artwork: the title row, the facts, the header buttons, the actions and the sections (on an overlay page, everything after the artwork)." },
    { name: 'detail.head', kind: 'part', description: 'The phone title row: the poster beside the alternative title, the title and the header template, pulled up into the artwork band.' },
    { name: 'detail.overview', kind: 'part', description: "The phone Overview's own content: the facts (with `sections.info: \"overview\"`) and the Synopsis, Information, Themes and Alternative titles blocks." },
    { name: 'detail.banner.fade', kind: 'part', description: 'The gradient that fades the phone artwork into the page: the bottom of the band, or the scrim under the text of an overlay page.' },
    { name: 'detail.airing.wrap', kind: 'part', description: 'The box holding `detail.airing` and its spacing (under the phone facts; on desktop, where the release timing leaves the episode toolbar). Hide it, not `detail.airing`, to drop the release timing with its margin.' },
    { name: 'detail.menu', kind: 'part', description: 'The phone More menu (the list button, "Download episodes" beside a header Download, and the tracker links), open while the More action (`detail.action` with `data-action="more"`) is expanded; with `detail.actions: "expand"` a tap on More while the row is unfolded opens it.' },
    { name: 'detail.home', kind: 'part', description: 'The Home link after Back in `detail.bar` (`detail.bar.home`).' },
    { name: 'detail.bar.logo', kind: 'part', description: 'The title logo inside `detail.bar.title` once the artwork has scrolled under the bar (`detail.bar.title: "logo"`).' },
    { name: 'detail.progress', kind: 'part', description: 'The phone series progress row under the header buttons (`detail.progress: "row"`), once the series is under way. `data-episode` is the episode Play opens and `--progress` the share watched ("31%").', states: ['data-episode'] },
    { name: 'detail.progress.label', kind: 'part', description: 'The progress row\'s "Episode 4 of 12".' },
    { name: 'detail.progress.value', kind: 'part', description: 'The share of the series watched ("31%").' },
    { name: 'detail.progress.meter', kind: 'part', description: 'The progress row\'s track; its child `span` is the fill.' },
  ],
  episodes: [
    { name: 'episode', kind: 'part', description: 'One episode: a card, a thumbnail row, a compact row or a number tile.', states: ['data-variant', 'data-state', 'data-next', 'data-filler'] },
    { name: 'episode.still', kind: 'part', description: 'The episode thumbnail.' },
    { name: 'episode.number', kind: 'part', description: 'The episode number.' },
    { name: 'episode.title', kind: 'part', description: 'The episode title.' },
    { name: 'episode.meta', kind: 'part', description: 'The line under an episode card title: the episode label, the airing countdown or Not aired.' },
    { name: 'episode.download', kind: 'part', description: 'An episode\'s own download button, the last control inside every episode card and row but the number tiles (`detail.episodes.download: "button"`; not offline, not in select mode, disabled before the episode airs). A press queues the episode with the Settings → Downloads defaults, or opens Downloads once it is queued, downloading or saved; it never plays the episode. `data-state` is `none`, `queued`, `progress` (downloading or paused) or `done`, and `--download-progress` the share downloaded ("42%").', states: ['data-state'] },
    { name: 'episodes.track', kind: 'part', description: 'The scrolling row holding the episode cards of a `carousel` arrangement. It opens with the episode the series Play button starts as its first card.' },
    { name: 'episodes.grid', kind: 'part', description: "The grid holding the episode cards (the cards layout, or a theme's `grid` arrangement); a stylesheet sets its columns." },
    { name: 'episodes.toolbar', kind: 'slot', description: "The episode controls: izumi's own bar, or the theme's bar or heading row (`detail.episodes.toolbar`).", states: ['data-variant'] },
    { name: 'episodes.sort', kind: 'part', description: 'The order control: Oldest and Newest options (`tabs`, the chosen one `data-active`) or one toggle naming the current order (`flip`).', states: ['data-variant', 'data-dir'] },
    { name: 'episodes.search', kind: 'part', description: 'The episode search: the field (holding `input`) or the button that opens it.', states: ['data-active'] },
    { name: 'episodes.layout', kind: 'part', description: "The phone cards/numbers switch: izumi's own bar shows both options (the chosen one `data-active`); a theme's toolbar shows one toggle to the other layout.", states: ['data-layout'] },
    { name: 'episodes.download', kind: 'part', description: 'The button that starts picking episodes to download.' },
    { name: 'episodes.queue', kind: 'part', description: 'The button that adds the next episode to the episode queue.' },
    { name: 'episodes.ranges', kind: 'part', description: 'The row of range chips above the list (`paging: "ranges"`); each range is a `chip`, the current one `data-active` and scrolled to the middle. The list opens on the range holding the episode the series Play button starts.' },
    { name: 'episodes.pager', kind: 'part', description: 'The Prev/Next row under the list; its buttons are `page-number`.' },
    { name: 'episodes.empty', kind: 'part', description: 'The line shown when a search matches no episode.' },
    { name: 'episodes.heading', kind: 'part', description: 'The "Episodes" heading of a heading-row toolbar (`toolbar: "header"`).' },
    { name: 'episodes.count', kind: 'part', description: 'The episode count beside the heading.' },
    { name: 'episodes.range', kind: 'part', description: 'The range picker button in the toolbar (`paging: "dropdown"`).', states: ['data-open'] },
    { name: 'episodes.more', kind: 'part', description: 'The overflow button holding the controls the toolbar does not show.' },
    { name: 'episodes.menu', kind: 'part', description: 'A menu opened from the episode controls: the overflow menu (a popover; a sheet on phones), the range list or the season list. It renders outside `detail.episodes`, at the end of the page, so select it directly rather than inside that slot.', states: ['data-variant'] },
    { name: 'episodes.seasons', kind: 'slot', description: 'The season picker above the episodes (`detail.episodes.seasons`); a `dropdown` in a heading-row toolbar takes the place of its heading. Its dropdown list is `episodes.menu` with `data-variant="seasons"`, which renders outside `detail.episodes`.', states: ['data-variant'] },
    { name: 'season', kind: 'part', description: 'One season: a chip, a poster or a list entry that opens that title.', states: ['data-active'] },
    { name: 'season.art', kind: 'part', description: 'The season cover (`posters`).' },
    { name: 'season.label', kind: 'part', description: 'The "Season N" label.' },
    { name: 'season.year', kind: 'part', description: "The season's year (`chips` and the dropdown list)." },
    { name: 'season.toggle', kind: 'part', description: 'The dropdown button showing the current season (`dropdown`).', states: ['data-open'] },
    { name: 'episode.continue', kind: 'part', description: 'The Continue card at the top of the episodes (`detail.continue: "card"`).', states: ['data-filler'] },
    { name: 'episode.continue.label', kind: 'part', description: 'The card\'s "Continue: Episode N" line ("Play: Episode N" before the series is started).' },
    { name: 'episode.continue.title', kind: 'part', description: "The card's episode title." },
  ],
  watch: [
    { name: 'watch', kind: 'slot', description: 'The player area; the scroller of a page-flow watch view with the episodes below the video.', states: ['data-layout', 'data-flow'] },
    { name: 'watch.stage', kind: 'slot', description: 'The video frame. It and its ancestors never paint a background: the video is drawn behind the page.' },
    { name: 'watch.page', kind: 'slot', description: 'The column of a page-flow watch view: the video frame, then the blocks under it (the scroller beside a side rail). An ancestor of the frame, so it never paints a background.' },
    { name: 'watch.block', kind: 'part', description: 'One block under a page-flow video, in `dock.below` order (beside a side rail, the discussion).', states: ['data-block'] },
    { name: 'watch.toolbar', kind: 'slot', description: 'The row of dropdowns under a docked video (`dock.below` `toolbar`).' },
    { name: 'watch.toolbar.item', kind: 'part', description: 'One dropdown button: the server, the episode, the release or the download.', states: ['data-item', 'data-state'] },
    { name: 'watch.toolbar.menu', kind: 'part', description: 'An open dropdown menu.', states: ['data-item'] },
    { name: 'watch.toolbar.option', kind: 'part', description: 'A menu entry; the current one is `data-state="active"`.', states: ['data-state'] },
    { name: 'watch.info', kind: 'slot', description: 'The info block under a docked video (`dock.below` `info`).' },
    { name: 'watch.info.poster', kind: 'part', description: 'The poster, linking to the series page.' },
    { name: 'watch.info.title', kind: 'part', description: '"Title - 12", the title linking to the series page.' },
    { name: 'watch.info.meta', kind: 'part', description: 'The format, episode count and airing state line.' },
    { name: 'watch.info.season', kind: 'part', description: 'The season line.' },
    { name: 'watch.rail', kind: 'slot', description: 'The rail beside or below a docked player.' },
    { name: 'watch.episodes', kind: 'slot', description: 'The docked episode list or grid.', states: ['data-variant'] },
    { name: 'watch.servers', kind: 'part', description: 'The server switcher.' },
    { name: 'watch.comments', kind: 'slot', description: 'The episode discussion (inline under a docked player, or the sheet).', states: ['data-variant'] },
    { name: 'comments.header', kind: 'part', description: 'The discussion heading row ("Discussion · Ep 12").' },
    { name: 'comments.tabs', kind: 'part', description: 'The row of discussion sources (All, then each source found).' },
    { name: 'comments.tab', kind: 'part', description: 'One discussion source.', states: ['data-active'] },
    { name: 'player.controls', kind: 'slot', description: 'The player controls layer.' },
    { name: 'player.seekbar', kind: 'part', description: 'The seek bar.' },
    { name: 'player.title', kind: 'part', description: 'The playing title.' },
  ],
  pages: [
    { name: 'search', kind: 'slot', description: 'The search page.', states: ['data-variant'] },
    { name: 'search.header', kind: 'slot', description: 'The Search page header: the title and the filter bar; on another catalog\'s page also the streaming service; on the all-catalogs page the field (or the chosen catalog\'s filter bar) under the catalog chips. It is a `display: contents` box, so the parts inside lay out (and stick) as they always did, until a theme gives it one: `display: block; position: sticky; top: 0` pins the whole header, and `:scope[data-chrome="hidden"]` can slide it away.' },
    { name: 'search.title', kind: 'part', description: 'The Search page heading: "Search" in the app language, visually hidden (`sr-only`) until a theme shows it, or with `data-variant="explore"` the genre, studio or voice actor being explored, shown. On the all-catalogs page it is the visible "Search" heading.', states: ['data-variant'] },
    { name: 'search.filters', kind: 'part', description: 'The search filter bar: the `search.field`, then the `search.filter` controls.' },
    { name: 'search.filter', kind: 'part', description: 'One control of the search filter bar, named by `data-filter` (`genres`, `format`, `status`, `season`, `year`, `sort`, `advanced`, `clear`; on other catalogs `type`, `genre`, `source`, `source-filters`), with `data-active` while it is set.', states: ['data-filter', 'data-active'] },
    { name: 'search.grid', kind: 'part', description: 'The grid holding the search results (`data-variant` `grid` or `list`); a stylesheet sets its gaps and columns. The placeholders shown while more results load are a second one with `data-state="loading"`.', states: ['data-variant', 'data-state'] },
    { name: 'search.results', kind: 'slot', description: 'The search results.' },
    { name: 'schedule', kind: 'slot', description: 'The airing schedule page.' },
    { name: 'schedule.day', kind: 'part', description: 'One day of airings: a day of the week agenda, or the selected day.' },
    { name: 'schedule.item', kind: 'part', description: 'One airing entry.' },
    { name: 'library', kind: 'slot', description: 'The library page.' },
    { name: 'library.tabs', kind: 'part', description: 'The library section tabs.' },
    { name: 'library.grid', kind: 'slot', description: 'The library card grid.' },
  ],
  primitives: [
    { name: 'button', kind: 'part', description: 'A button. Series page actions carry `data-action` (Save also `data-state="saved"`; every Play button `data-state` `start` or `resume`, the episode it opens in `data-episode` and, when the episode metadata knows it, that episode\'s season in `data-season` and its number within the season in `data-season-episode`; the header\'s Download `data-state` `none`, `queued`, `progress` or `done` and the episode it queues in `data-episode`); profile-header shortcuts carry their destination in `data-dest`.', states: ['data-variant', 'data-action', 'data-dest', 'data-state', 'data-episode', 'data-season', 'data-season-episode'] },
    { name: 'chip', kind: 'part', description: 'A chip or pill (genre, tag, alternative title, filter, scope, episode range). A tag carries its rank in `data-rank`.', states: ['data-active', 'data-rank'] },
    { name: 'chip.meta', kind: 'part', description: 'Extra text at the end of a chip, hidden (`display: none`) until a theme shows it: a tag\'s rank ("94%"). Where izumi prints the rank itself (reading pages), it shows after " · ".' },
    { name: 'input', kind: 'part', description: 'A text input.' },
    { name: 'badge', kind: 'part', description: 'A small label on an item (for example an episode rating).' },
    { name: 'tabs', kind: 'part', description: 'A tab strip.', states: ['data-variant'] },
    { name: 'tab', kind: 'part', description: 'One tab. Series page tabs carry their section id.', states: ['data-active', 'data-tab'] },
  ],
}
