/** The documented styling hooks theme stylesheets may target (docs/THEMES.md "Styling hooks").
 *  A `slot` is a page region (`data-slot`), a `part` a component (`data-part`). Renaming or
 *  removing one breaks published themes; hooks.test.ts keeps this list and the markup in step.
 *  In markup, write hook names as string literals — `data-part="card"` or
 *  `data-slot={top ? 'nav.top' : 'nav.side'}` — and never put any other quoted string inside a
 *  `data-slot`/`data-part` expression: the test reads every quoted literal there as a hook name. */
export interface ThemeHook {
  name: string
  kind: 'slot' | 'part'
  description: string
  /** State attributes rendered alongside, e.g. `data-active`. */
  states?: string[]
}
export type ThemeHookGroup = 'shell' | 'home' | 'blocks' | 'cards' | 'detail' | 'episodes' | 'watch' | 'pages' | 'primitives'

export const THEME_HOOKS: Partial<Record<ThemeHookGroup, ThemeHook[]>> = {
  shell: [
    { name: 'page', kind: 'slot', description: 'The routed page content (the app <main>).' },
    { name: 'nav.side', kind: 'slot', description: 'The side navigation rail.' },
    { name: 'nav.top', kind: 'slot', description: 'The top navigation bar (shell.nav "top").' },
    { name: 'nav.bottom', kind: 'slot', description: 'The bottom tab bar (phones, or shell.nav "bottom").' },
    { name: 'nav.item', kind: 'part', description: 'A navigation destination link, or the Categories menu button (`data-variant="menu"`).', states: ['data-active', 'data-variant'] },
    { name: 'nav.item.icon', kind: 'part', description: 'The icon of a navigation destination.' },
    { name: 'nav.item.label', kind: 'part', description: 'The label of a navigation destination.' },
    { name: 'search.field', kind: 'part', description: "A search input: the global search overlay, or the theme top bar's search field." },
    { name: 'search.suggestions', kind: 'part', description: "The live results panel under the top bar's search field while typing." },
    { name: 'search.suggestion', kind: 'part', description: 'One live result; the keyboard-highlighted one has `data-active`.', states: ['data-active'] },
    { name: 'search.suggestion.poster', kind: 'part', description: "A live result's poster." },
    { name: 'search.suggestion.title', kind: 'part', description: "A live result's title." },
    { name: 'search.suggestion.meta', kind: 'part', description: 'The format, episode count, year and status line of a live result.' },
    { name: 'search.suggestion.all', kind: 'part', description: 'The "View all results" link at the end of the panel.' },
    { name: 'nav.menu', kind: 'part', description: 'The top bar menu button that opens the drawer.' },
    { name: 'nav.drawer', kind: 'slot', description: 'The side drawer of destinations (top bar `menu: "drawer"`); items are `nav.item`.' },
    { name: 'nav.panel', kind: 'slot', description: 'The pinned menu panel down the left (top bar `menu: "side"`); items are `nav.item`.' },
    { name: 'nav.categories', kind: 'slot', description: 'The Categories menu panel (top bar `categories`).' },
    { name: 'nav.categories.heading', kind: 'part', description: 'The Genres heading in the Categories menu.' },
    { name: 'nav.categories.link', kind: 'part', description: 'A Categories menu link; genre links carry `data-variant="genre"`.', states: ['data-variant'] },
    { name: 'hints.glyph', kind: 'part', description: "A controller button's printed label: round for face buttons, a pill for bumpers, triggers and the menu buttons.", states: ['data-button', 'data-family'] },
  ],
  home: [
    { name: 'home', kind: 'slot', description: 'The Home page.', states: ['data-variant'] },
    { name: 'home.hero', kind: 'slot', description: 'The featured banner on Home.', states: ['data-variant'] },
    { name: 'hero.slide', kind: 'part', description: 'The current slide (the artwork layer).' },
    { name: 'hero.art', kind: 'part', description: 'The slide artwork image.' },
    { name: 'hero.scrim', kind: 'part', description: 'A gradient over the artwork.' },
    { name: 'hero.logo', kind: 'part', description: 'The title logo, when the show has one.' },
    { name: 'hero.title', kind: 'part', description: 'The text title, when there is no logo.' },
    { name: 'hero.meta', kind: 'part', description: 'The facts line (format, episodes, score, status).' },
    { name: 'hero.synopsis', kind: 'part', description: 'The description (desktop).' },
    { name: 'hero.actions', kind: 'part', description: 'The Watch, Details and Favorite buttons.' },
    { name: 'hero.indicator', kind: 'part', description: 'The slide marker row.', states: ['data-variant'] },
    { name: 'hero.dot', kind: 'part', description: 'One slide marker.', states: ['data-active', 'data-past'] },
    { name: 'hero.dot.track', kind: 'part', description: 'The drawn shape of a slide marker (its bar, dot or pill).' },
    { name: 'hero.dot.fill', kind: 'part', description: 'The timed fill inside a bar marker (indicator style `bars`).' },
    { name: 'hero.counter', kind: 'part', description: 'The "n / N" counter (indicator style "counter").' },
    { name: 'row', kind: 'slot', description: 'A titled row or grid of cards, on Home and elsewhere. Home rows carry their stable id and role.', states: ['data-row', 'data-role', 'data-layout'] },
    { name: 'row.header', kind: 'part', description: 'The row heading bar.' },
    { name: 'row.title', kind: 'part', description: 'The row title.' },
    { name: 'row.more', kind: 'part', description: "The row's view-more link." },
    { name: 'row.track', kind: 'part', description: 'The scrolling track or grid holding the cards.' },
  ],
  blocks: [
    { name: 'home.header', kind: 'slot', description: 'The phone Home app bar: the wordmark and the top icons.' },
    { name: 'home.main', kind: 'slot', description: 'The main column of Home; the rows above the side column (`layout.asideStart`) are a second one with `data-variant="lead"`.', states: ['data-variant'] },
    { name: 'home.aside', kind: 'slot', description: 'The side column of Home, holding blocks placed in the aside.' },
    { name: 'pagination', kind: 'part', description: 'Page controls under a block: numbered pages or a Load more button.' },
    { name: 'page-number', kind: 'part', description: 'A page button: a numbered page under a block, Prev/Next under the episode list, or an entry of the episode range picker.', states: ['data-active'] },
    { name: 'block.title', kind: 'part', description: 'A block heading.' },
    { name: 'block.genre-chips', kind: 'slot', description: 'Genre shortcuts: an All chip and one chip per genre (each a `chip`).' },
    { name: 'block.latest-episodes', kind: 'slot', description: 'Newly aired episodes as a grid of stills. Items reuse `episode.still`, `episode.number`, `card.title` and `card.meta`. `data-caption` is `below` or `overlay`.', states: ['data-caption'] },
    { name: 'block.item', kind: 'part', description: 'One entry in a block (an episode, a poster, a ranked title or an airing).', states: ['data-aired'] },
    { name: 'block.tabbed-grid', kind: 'slot', description: 'A tab strip (`tabs`) over a poster grid; each poster is a `block.item` holding a `card`.' },
    { name: 'block.ranked-list', kind: 'slot', description: 'A numbered top list; each entry is a `block.item` with `card.art`, `card.title` and `card.meta`.' },
    { name: 'block.rank', kind: 'part', description: 'The rank number of a ranked-list entry.' },
    { name: 'block.profile-header', kind: 'slot', description: 'The profile banner with the viewer\'s name, watch stats and shortcut buttons (`button`).' },
    { name: 'block.banner', kind: 'part', description: 'The profile banner image.' },
    { name: 'block.avatar', kind: 'part', description: 'The profile avatar (an image, or the first letter of the name).' },
    { name: 'block.name', kind: 'part', description: 'The profile name.' },
    { name: 'block.stat', kind: 'part', description: 'The watch statistics line.' },
    { name: 'block.airing-today', kind: 'slot', description: "Today's airings in time order; each entry is a `block.item` with `airing.poster`, `airing.title` and `airing.time`, and `data-aired` once it has aired." },
    { name: 'block.more', kind: 'part', description: "A block's link to its full page (the schedule, on airing-today)." },
    { name: 'block.clock', kind: 'part', description: 'The date (`block.clock.date`) and live clock (`block.clock.time`) under an airing-today heading.' },
    { name: 'block.clock.date', kind: 'part', description: "Today's date in an airing-today clock." },
    { name: 'block.clock.time', kind: 'part', description: 'The live time in an airing-today clock.' },
    { name: 'airing.poster', kind: 'part', description: 'The poster of an airing-today entry.' },
    { name: 'airing.title', kind: 'part', description: 'The series title of an airing-today entry.' },
    { name: 'airing.time', kind: 'part', description: 'The local airing time of an airing-today entry: a tick once aired, a clock before.' },
  ],
  cards: [
    { name: 'card', kind: 'part', description: 'A media card: poster, search, continue or preview.', states: ['data-family'] },
    { name: 'card.art', kind: 'part', description: 'The card artwork frame.' },
    { name: 'card.title', kind: 'part', description: 'The card title.' },
    { name: 'card.meta', kind: 'part', description: 'The line under the title (season, format, source, episode).' },
    { name: 'card.badge', kind: 'part', description: 'The label on the artwork (for example "Episode 5").' },
    { name: 'card.score', kind: 'part', description: 'The score badge.' },
    { name: 'card.progress', kind: 'part', description: 'The watch-progress track; the fill is its child.' },
    { name: 'card.episode', kind: 'part', description: 'The episode number on resume cards.' },
    { name: 'card.overlay', kind: 'part', description: 'The hover or play overlay on the artwork.' },
  ],
  detail: [
    { name: 'detail', kind: 'slot', description: 'The series page.', states: ['data-layout', 'data-variant'] },
    { name: 'detail.banner', kind: 'slot', description: 'The artwork area at the top of the series page.' },
    { name: 'detail.poster', kind: 'part', description: 'The cover image.' },
    { name: 'detail.column', kind: 'slot', description: 'The left column headed by the poster (`detail.column: "poster"`): the trailer button, the countdown and the facts.' },
    { name: 'detail.trailer', kind: 'part', description: 'The labelled Watch Trailer button in the poster column.' },
    { name: 'detail.title', kind: 'part', description: 'The title.' },
    { name: 'detail.logo', kind: 'part', description: 'The title logo inside `detail.title` (`detail.title: "logo"`).' },
    { name: 'detail.backdrop', kind: 'part', description: 'The artwork behind an overlay series page: the banner, key art (`detail.art: "keyart"`) or a blurred cover.' },
    { name: 'detail.body', kind: 'part', description: 'The text column over the artwork of an overlay series page.' },
    { name: 'detail.studio', kind: 'part', description: 'The studio line of the desktop overlay page.' },
    { name: 'detail.rating', kind: 'part', description: 'The rating row (your score) of the desktop overlay page.' },
    { name: 'detail.alt-title', kind: 'part', description: 'The native or romaji title.' },
    { name: 'detail.header', kind: 'part', description: 'The theme template under the title (`detail.header`).' },
    { name: 'detail.meta', kind: 'part', description: 'The facts line.' },
    { name: 'detail.facts', kind: 'part', description: 'The facts: a theme template (stacked and split layouts, on phones and desktop) or, with `detail.factsStyle`, a table, cards or chips.', states: ['data-variant'] },
    { name: 'fact', kind: 'part', description: 'One fact: an entry of the details grid, or a table row, card or chip of `detail.facts`.', states: ['data-key'] },
    { name: 'fact.label', kind: 'part', description: 'A details entry label.' },
    { name: 'fact.value', kind: 'part', description: 'A details entry value.' },
    { name: 'detail.genres', kind: 'part', description: 'The genre chips (phone).' },
    { name: 'detail.synopsis', kind: 'part', description: 'The description.' },
    { name: 'detail.actions', kind: 'part', description: 'The action buttons row.' },
    { name: 'detail.list-button', kind: 'part', description: 'The tracker list-status button.', states: ['data-variant', 'data-action'] },
    { name: 'detail.action', kind: 'part', description: 'A series action that is not a `button`: Trailer, and on phones More (whose menu holds the list button and tracker links).', states: ['data-action'] },
    { name: 'detail.airing', kind: 'part', description: 'The release status of upcoming episodes (sub and dub timing, delays).' },
    { name: 'detail.countdown', kind: 'part', description: 'The next-episode countdown (`detail.countdown` compact or long).', states: ['data-variant'] },
    { name: 'detail.episodes', kind: 'slot', description: 'The episode list.' },
    { name: 'detail.relations', kind: 'slot', description: 'Related titles.' },
    { name: 'relation.type', kind: 'part', description: 'The relation above a related title ("sequel", "side story").' },
    { name: 'detail.characters', kind: 'slot', description: 'Characters and voice actors.' },
    { name: 'detail.staff', kind: 'slot', description: 'Staff credits.' },
    { name: 'detail.bar', kind: 'slot', description: 'The floating top bar of the phone series page (back and, once scrolled, the title).', states: ['data-solid'] },
    { name: 'detail.byline', kind: 'part', description: 'The phone studio · source · members line.' },
    { name: 'person', kind: 'part', description: 'One character or staff credit.' },
    { name: 'person.photo', kind: 'part', description: "The credit's picture." },
    { name: 'person.name', kind: 'part', description: 'The character or staff name.' },
    { name: 'person.role', kind: 'part', description: "The character's role or the staff job." },
    { name: 'detail.section', kind: 'slot', description: 'A titled section outside the tab strip: every section with `sections.mode: "stack"`, or a section without a tab inside Overview.', states: ['data-section'] },
    { name: 'detail.section-title', kind: 'part', description: 'The heading of a `detail.section`.' },
  ],
  episodes: [
    { name: 'episode', kind: 'part', description: 'One episode: a card, a thumbnail row, a compact row or a number tile.', states: ['data-variant', 'data-state', 'data-next', 'data-filler'] },
    { name: 'episode.still', kind: 'part', description: 'The episode thumbnail.' },
    { name: 'episode.number', kind: 'part', description: 'The episode number.' },
    { name: 'episode.title', kind: 'part', description: 'The episode title.' },
    { name: 'episodes.track', kind: 'part', description: 'The scrolling row holding the episode cards of a `carousel` arrangement.' },
    { name: 'episodes.grid', kind: 'part', description: "The grid holding the episode cards (the cards layout, or a theme's `grid` arrangement); a stylesheet sets its columns." },
    { name: 'episodes.toolbar', kind: 'slot', description: "The episode controls: izumi's own bar, or the theme's bar or heading row (`detail.episodes.toolbar`).", states: ['data-variant'] },
    { name: 'episodes.sort', kind: 'part', description: 'The order control: Oldest and Newest options (`tabs`, the chosen one `data-active`) or one toggle naming the current order (`flip`).', states: ['data-variant', 'data-dir'] },
    { name: 'episodes.search', kind: 'part', description: 'The episode search: the field (holding `input`) or the button that opens it.', states: ['data-active'] },
    { name: 'episodes.layout', kind: 'part', description: "The phone cards/numbers switch: izumi's own bar shows both options (the chosen one `data-active`); a theme's toolbar shows one toggle to the other layout.", states: ['data-layout'] },
    { name: 'episodes.download', kind: 'part', description: 'The button that starts picking episodes to download.' },
    { name: 'episodes.queue', kind: 'part', description: 'The button that adds the next episode to the episode queue.' },
    { name: 'episodes.ranges', kind: 'part', description: 'The row of range chips above the list (`paging: "ranges"`); each range is a `chip`, the current one `data-active`.' },
    { name: 'episodes.pager', kind: 'part', description: 'The Prev/Next row under the list; its buttons are `page-number`.' },
    { name: 'episodes.empty', kind: 'part', description: 'The line shown when a search matches no episode.' },
    { name: 'episodes.heading', kind: 'part', description: 'The "Episodes" heading of a heading-row toolbar (`toolbar: "header"`).' },
    { name: 'episodes.count', kind: 'part', description: 'The episode count beside the heading.' },
    { name: 'episodes.range', kind: 'part', description: 'The range picker button in the toolbar (`paging: "dropdown"`).', states: ['data-open'] },
    { name: 'episodes.more', kind: 'part', description: 'The overflow button holding the controls the toolbar does not show.' },
    { name: 'episodes.menu', kind: 'part', description: 'A menu opened from the episode controls: the overflow menu (a popover; a sheet on phones), the range list or the season list. It renders outside `detail.episodes`, at the end of the page, so select it directly rather than inside that slot.', states: ['data-variant'] },
    { name: 'episodes.seasons', kind: 'slot', description: 'The season picker above the episodes (`detail.episodes.seasons`); a `dropdown` in a heading-row toolbar takes the place of its heading. Its dropdown list is `episodes.menu` with `data-variant="seasons"`, which renders outside `detail.episodes`.', states: ['data-variant'] },
    { name: 'season', kind: 'part', description: 'One season: a chip, a poster or a list entry that opens that title.', states: ['data-active'] },
    { name: 'season.art', kind: 'part', description: 'The season cover (`posters`).' },
    { name: 'season.label', kind: 'part', description: 'The "Season N" label.' },
    { name: 'season.year', kind: 'part', description: "The season's year (`chips` and the dropdown list)." },
    { name: 'season.toggle', kind: 'part', description: 'The dropdown button showing the current season (`dropdown`).', states: ['data-open'] },
    { name: 'episode.continue', kind: 'part', description: 'The Continue card at the top of the episodes (`detail.continue: "card"`).', states: ['data-filler'] },
    { name: 'episode.continue.label', kind: 'part', description: 'The card\'s "Continue: Episode N" line ("Play: Episode N" before the series is started).' },
    { name: 'episode.continue.title', kind: 'part', description: "The card's episode title." },
  ],
  watch: [
    { name: 'watch', kind: 'slot', description: 'The player area; the scroller of a page-flow watch view.', states: ['data-layout', 'data-flow'] },
    { name: 'watch.stage', kind: 'slot', description: 'The video frame. It and its ancestors never paint a background: the video is drawn behind the page.' },
    { name: 'watch.page', kind: 'slot', description: 'The column of a page-flow watch view: the video frame, then the blocks under it. An ancestor of the frame, so it never paints a background.' },
    { name: 'watch.block', kind: 'part', description: 'One block under a page-flow video, in `dock.below` order.', states: ['data-block'] },
    { name: 'watch.toolbar', kind: 'slot', description: 'The row of dropdowns under a docked video (`dock.below` `toolbar`).' },
    { name: 'watch.toolbar.item', kind: 'part', description: 'One dropdown button: the server, the episode, the release or the download.', states: ['data-item', 'data-state'] },
    { name: 'watch.toolbar.menu', kind: 'part', description: 'An open dropdown menu.', states: ['data-item'] },
    { name: 'watch.toolbar.option', kind: 'part', description: 'A menu entry; the current one is `data-state="active"`.', states: ['data-state'] },
    { name: 'watch.info', kind: 'slot', description: 'The info block under a docked video (`dock.below` `info`).' },
    { name: 'watch.info.poster', kind: 'part', description: 'The poster, linking to the series page.' },
    { name: 'watch.info.title', kind: 'part', description: '"Title - 12", the title linking to the series page.' },
    { name: 'watch.info.meta', kind: 'part', description: 'The format, episode count and airing state line.' },
    { name: 'watch.info.season', kind: 'part', description: 'The season line.' },
    { name: 'watch.rail', kind: 'slot', description: 'The rail beside or below a docked player.' },
    { name: 'watch.episodes', kind: 'slot', description: 'The docked episode list or grid.', states: ['data-variant'] },
    { name: 'watch.servers', kind: 'part', description: 'The server switcher.' },
    { name: 'watch.comments', kind: 'slot', description: 'The episode discussion (inline under a docked player, or the sheet).', states: ['data-variant'] },
    { name: 'comments.header', kind: 'part', description: 'The discussion heading row ("Discussion · Ep 12").' },
    { name: 'comments.tabs', kind: 'part', description: 'The row of discussion sources (All, then each source found).' },
    { name: 'comments.tab', kind: 'part', description: 'One discussion source.', states: ['data-active'] },
    { name: 'player.controls', kind: 'slot', description: 'The player controls layer.' },
    { name: 'player.seekbar', kind: 'part', description: 'The seek bar.' },
    { name: 'player.title', kind: 'part', description: 'The playing title.' },
  ],
  pages: [
    { name: 'search', kind: 'slot', description: 'The search page.', states: ['data-variant'] },
    { name: 'search.filters', kind: 'part', description: 'The search filter bar.' },
    { name: 'search.results', kind: 'slot', description: 'The search results.' },
    { name: 'schedule', kind: 'slot', description: 'The airing schedule page.' },
    { name: 'schedule.day', kind: 'part', description: 'One day of airings: a day of the week agenda, or the selected day.' },
    { name: 'schedule.item', kind: 'part', description: 'One airing entry.' },
    { name: 'library', kind: 'slot', description: 'The library page.' },
    { name: 'library.tabs', kind: 'part', description: 'The library section tabs.' },
    { name: 'library.grid', kind: 'slot', description: 'The library card grid.' },
  ],
  primitives: [
    { name: 'button', kind: 'part', description: 'A button. Series page actions carry `data-action`.', states: ['data-variant', 'data-action'] },
    { name: 'chip', kind: 'part', description: 'A chip or pill (genre, filter, scope, episode range).', states: ['data-active'] },
    { name: 'input', kind: 'part', description: 'A text input.' },
    { name: 'badge', kind: 'part', description: 'A small label on an item (for example an episode rating).' },
    { name: 'tabs', kind: 'part', description: 'A tab strip.', states: ['data-variant'] },
    { name: 'tab', kind: 'part', description: 'One tab. Series page tabs carry their section id.', states: ['data-active', 'data-tab'] },
  ],
}
