import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const detail = readFileSync(fileURLToPath(new URL('./AnimeDetail.svelte', import.meta.url)), 'utf8')
const list = readFileSync(fileURLToPath(new URL('./EpisodeList.svelte', import.meta.url)), 'utf8')
const card = readFileSync(fileURLToPath(new URL('./EpisodeCard.svelte', import.meta.url)), 'utf8')

describe('themed series page composition', () => {
  it('reads placement from the presentation contract instead of a one-off flag', () => {
    expect(detail).toContain('resolveDetail($themePresentation)')
    expect(detail).toContain('episodesOnSide($themePresentation, !$isMobile)')
    expect(detail).toContain('episodesBelow($themePresentation, !$isMobile)')
    expect(detail).toContain('overlayDetail')
    expect(detail).toContain('sideEpisodes')
    expect(detail).toContain('minmax(22rem,40%)')
    expect(detail).toContain('data-theme-surface="detail-overlay"')
  })
  it('keeps the play-to-episode gamepad lane when the rail moves', () => {
    expect(detail).toContain('data-nav-id="series-primary-action"')
    expect(detail).toContain("data-nav-down={controllerUi ? 'series-quick-episode' : undefined}")
    expect(list).toContain("data-nav-id={ep === quickEpisode ? 'series-quick-episode' : undefined}")
  })
  it('renders episode templates inside the host-owned play control', () => {
    expect(list).toContain('themeCard={episodeCard}')
    expect(list).toContain('episodeListLayout')
    expect(list).toContain("arrangement === 'list'")
    expect(list).toContain("arrangement === 'carousel'")
    expect(list).toContain("arrangement === 'grid'")
    expect(list).toContain('episodeGridLayout')
    expect(list).toContain('w-[min(100%,18rem)]')
    expect(list).toContain('gap-3 min-[500px]:grid-cols-2')
    expect(list).toContain("episodeTheme?.placement === 'right' ? 'min-[960px]:max-h-[calc(100vh-5rem)] min-[960px]:overflow-y-auto'")
    expect(detail).toContain("gap-x-6 gap-y-8' : 'gap-4'")
    expect(detail).toContain("shrink-0' : 'w-[152px]'")
    expect(card).toContain('{#if themeCard}')
    expect(card).toContain('<ThemeNode node={themeCard}')
    expect(card).toContain("themeCard ? (listRow ? 'flex w-full min-w-0' : 'flex w-full min-w-0 flex-col')")
    expect(card).toContain('still: img || cover(media)')
    expect(card).toContain('episodeTitle: labels.primary || `Episode ${ep}`')
    expect(card).toContain('hoverScale')
    expect(card).toContain('labels.concealSecondary')
    expect(card).not.toContain('description: labels.concealSecondary ? undefined : labels.secondary')
    expect(card).not.toContain('actions={{ play:')
  })
  it('lets a series-facts template replace the default dotted metadata line', () => {
    expect(detail).toContain('detailTheme.facts')
    expect(detail).toContain('<ThemeNode node={detailTheme.facts}')
    expect(detail).toContain('bannerOverlap')
    expect(detail).toContain('bannerHeight')
    expect(detail).toContain('bannerScale')
    expect(card).not.toContain('ring-1 ring-white')
    expect(list).toContain('episode-scale')
    expect(list).toContain('episode-order-flip')
    expect(list).toContain('episode-load-in')
    expect(detail).toContain("detailTheme.episodes?.order === 'flip'")
    expect(detail).toContain('pt-[7.5rem]')
    expect(detail).toContain("detailTheme.bannerScale === 'banner' ? 'md:pt-12'")
    expect(list).not.toContain('episode-rail-flip')
    expect(list).not.toContain('Random')
  })
  it('collapses a right-hand rail on the phone layout', () => {
    expect(detail).toContain('{#if belowEpisodes}')
    expect(detail).toContain('mobileTabs')
  })
})
