#!/usr/bin/env bash
# Scaffold + patch the Android Gradle project for a CI build.
#
# `gen/android` is gitignored and regenerated by `tauri android init`, so every project tweak has
# to be re-applied on each run — it cannot be committed. Shared by the release matrix and the PR
# preview build so the two cannot drift: a patch that lands here is in both, and every patch
# verifies itself rather than silently no-oping when the scaffold template changes.
#
# Usage: scripts/ci/android-scaffold.sh <lite|full>
set -euo pipefail

FLAVOR="${1:?usage: android-scaffold.sh <lite|full>}"
case "$FLAVOR" in
  lite|full) ;;
  *) echo "unknown flavor: $FLAVOR (expected lite or full)"; exit 1 ;;
esac

npx tauri android init

# Android 16 / API 36 is required for Play submissions from 2026-08-31. Pin both generated
# values instead of relying on whichever defaults happen to ship in the installed Tauri CLI.
sed -i -E 's/compileSdk = [0-9]+/compileSdk = 36/' src-tauri/gen/android/app/build.gradle.kts
sed -i -E 's/targetSdk = [0-9]+/targetSdk = 36/' src-tauri/gen/android/app/build.gradle.kts
sed -i -E 's#androidx\.webkit:webkit:[0-9.]+#androidx.webkit:webkit:1.17.0#' src-tauri/gen/android/app/build.gradle.kts
grep -q 'compileSdk = 36' src-tauri/gen/android/app/build.gradle.kts \
  || { echo "compileSdk 36 patch missed — scaffold shape changed"; exit 1; }
grep -q 'targetSdk = 36' src-tauri/gen/android/app/build.gradle.kts \
  || { echo "targetSdk 36 patch missed — scaffold shape changed"; exit 1; }
grep -q 'androidx.webkit:webkit:1.17.0' src-tauri/gen/android/app/build.gradle.kts \
  || { echo "AndroidX WebKit 1.17 patch missed — scaffold shape changed"; exit 1; }

# NOTE on back navigation: an earlier revision patched the generated WryActivity's back-press
# fall-through here. That was doubly wrong. (1) WryActivity.kt is written by wry's BUILD SCRIPT
# during `tauri android build`, not by `tauri android init` — at scaffold time the file does not
# exist on a fresh checkout (the find below failed CI), and wry rewrites any file whose content
# differs from its template, so a patch could never survive the build anyway. (2) The code being
# patched is unreachable: the generated TauriActivity sets `handleBackNavigation = false`, so
# wry's back callback — the only caller of the patched line — is never registered in a Tauri app.
# Back-press behavior is what it was in every prior release; changing it belongs in MainActivity
# (app-owned, patchable here) via wry's `open` hooks, not in wry's regenerated file.

# The generated MainActivity already opts into AndroidX's inset handling. Make a template change
# fail the build rather than silently shipping content under the status/navigation bars.
MAIN_ACTIVITY="$(find src-tauri/gen/android/app/src/main/java -name MainActivity.kt -print -quit)"
test -n "$MAIN_ACTIVITY" || { echo "generated MainActivity.kt not found"; exit 1; }
grep -q 'enableEdgeToEdge()' "$MAIN_ACTIVITY" \
  || { echo "edge-to-edge setup missing from MainActivity"; exit 1; }

# Reqwest's rustls backend delegates certificate verification to Android. The Rust verifier needs
# both its bundled Kotlin component and a JVM Context before any async HTTP worker starts. Load the
# native library and initialize it before `super.onCreate`: Tauri starts the Rust app from inside
# that call, so doing this afterwards leaves a race with startup sync and source requests.
CARGO_BIN="$(command -v cargo || command -v cargo.exe)" \
  || { echo "cargo not found while locating rustls Android support"; exit 1; }
NODE_BIN="$(command -v node || command -v node.exe)" \
  || { echo "node not found while locating rustls Android support"; exit 1; }
RUSTLS_ANDROID_MANIFEST="$(
  "$CARGO_BIN" metadata \
    --manifest-path src-tauri/Cargo.toml \
    --format-version 1 \
    --filter-platform aarch64-linux-android \
    | "$NODE_BIN" -e 'let input=""; process.stdin.on("data", chunk => input += chunk); process.stdin.on("end", () => { const pkg = JSON.parse(input).packages.find(candidate => candidate.name === "rustls-platform-verifier-android"); if (!pkg) process.exit(1); process.stdout.write(pkg.manifest_path); });'
)" || { echo "rustls Android support crate not found in Cargo metadata"; exit 1; }
if command -v wslpath >/dev/null && [[ "$RUSTLS_ANDROID_MANIFEST" =~ ^[A-Za-z]:\\ ]]; then
  RUSTLS_ANDROID_MANIFEST="$(wslpath -u "$RUSTLS_ANDROID_MANIFEST")"
fi
RUSTLS_ANDROID_AAR="$(find "$(dirname "$RUSTLS_ANDROID_MANIFEST")/maven" -name '*.aar' -print -quit)"
test -s "$RUSTLS_ANDROID_AAR" \
  || { echo "rustls Android verifier AAR not found"; exit 1; }
mkdir -p src-tauri/gen/android/app/libs
cp "$RUSTLS_ANDROID_AAR" src-tauri/gen/android/app/libs/rustls-platform-verifier.aar
cp src-tauri/android/AndroidTlsVerifier.kt "$(dirname "$MAIN_ACTIVITY")/AndroidTlsVerifier.kt"
cp src-tauri/android/MainActivity.kt "$MAIN_ACTIVITY"
cp src-tauri/android/proguard-rustls.pro src-tauri/gen/android/app/proguard-rustls.pro
sed -i '/implementation(files("libs\/rustls-platform-verifier.aar"))/d' \
  src-tauri/gen/android/app/build.gradle.kts
sed -i '/dependencies {/a\    implementation(files("libs/rustls-platform-verifier.aar"))' \
  src-tauri/gen/android/app/build.gradle.kts
test "$(grep -c 'implementation(files("libs/rustls-platform-verifier.aar"))' src-tauri/gen/android/app/build.gradle.kts)" -eq 1 \
  || { echo "rustls Android verifier dependency is missing or duplicated"; exit 1; }
test "$(grep -c 'AndroidTlsVerifier.initialize(applicationContext)' "$MAIN_ACTIVITY")" -eq 1 \
  || { echo "rustls Android verifier startup hook is missing or duplicated"; exit 1; }

# `android init` synthesizes launcher resources from the generic desktop icon and can overwrite the
# hand-tuned adaptive foreground. Install the canonical Izumi Android resources after scaffolding so
# both the APK installer preview and launcher use Izumi, never Tauri's template icon. Also declare
# the dedicated circular legacy asset.
cp -R src-tauri/icons/android/. src-tauri/gen/android/app/src/main/res/
if ! grep -q 'android:roundIcon=' src-tauri/gen/android/app/src/main/AndroidManifest.xml; then
  sed -i 's#android:icon="@mipmap/ic_launcher"#android:icon="@mipmap/ic_launcher"\n        android:roundIcon="@mipmap/ic_launcher_round"#' src-tauri/gen/android/app/src/main/AndroidManifest.xml
fi
if ! grep -q 'android:banner=' src-tauri/gen/android/app/src/main/AndroidManifest.xml; then
  sed -i 's#android:roundIcon="@mipmap/ic_launcher_round"#android:roundIcon="@mipmap/ic_launcher_round"\n        android:banner="@drawable/izumi_tv_banner"#' src-tauri/gen/android/app/src/main/AndroidManifest.xml
fi
cmp src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher.png \
    src-tauri/gen/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
cmp src-tauri/icons/android/drawable-xhdpi/izumi_tv_banner.png \
    src-tauri/gen/android/app/src/main/res/drawable-xhdpi/izumi_tv_banner.png
grep -q '#0E1524' src-tauri/gen/android/app/src/main/res/values/ic_launcher_background.xml

# One APK serves handheld Android and television devices. Leanback remains optional for phones,
# while touchscreen/faketouch are explicitly optional so Play can offer the app to remote-only TVs.
if ! grep -q 'android.software.leanback' src-tauri/gen/android/app/src/main/AndroidManifest.xml; then
  sed -i 's#    <application#    <uses-feature android:name="android.software.leanback" android:required="false" />\n    <uses-feature android:name="android.hardware.touchscreen" android:required="false" />\n    <uses-feature android:name="android.hardware.faketouch" android:required="false" />\n\n    <application#' \
    src-tauri/gen/android/app/src/main/AndroidManifest.xml
fi
if ! grep -q 'android.intent.category.LEANBACK_LAUNCHER' src-tauri/gen/android/app/src/main/AndroidManifest.xml; then
  sed -i '/android.intent.category.LAUNCHER/a\                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />' \
    src-tauri/gen/android/app/src/main/AndroidManifest.xml
fi
grep -q 'android:banner="@drawable/izumi_tv_banner"' src-tauri/gen/android/app/src/main/AndroidManifest.xml \
  || { echo "Android TV banner patch missed"; exit 1; }
grep -q 'android.hardware.touchscreen" android:required="false"' src-tauri/gen/android/app/src/main/AndroidManifest.xml \
  || { echo "Android TV touchscreen declaration patch missed"; exit 1; }
grep -q 'android.intent.category.LEANBACK_LAUNCHER' src-tauri/gen/android/app/src/main/AndroidManifest.xml \
  || { echo "Android TV launcher patch missed"; exit 1; }
grep -q 'IzumiTV/1' "$MAIN_ACTIVITY" \
  || { echo "Android TV activity marker is missing"; exit 1; }

# navigator.onLine only reflects real connectivity when the app holds ACCESS_NETWORK_STATE; without
# it the WebView always reports online, so offline mode's launch auto-detect + the offline banner
# never fire on Android. Applies to BOTH flavors (both are WebView apps).
sed -i '/<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" \/>/d' \
  src-tauri/gen/android/app/src/main/AndroidManifest.xml
sed -i 's#<uses-permission android:name="android.permission.INTERNET" />#<uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />#' \
  src-tauri/gen/android/app/src/main/AndroidManifest.xml
test "$(grep -c 'android.permission.ACCESS_NETWORK_STATE' src-tauri/gen/android/app/src/main/AndroidManifest.xml)" -eq 1 \
  || { echo "ACCESS_NETWORK_STATE permission is missing or duplicated"; exit 1; }

# Kotlin toolchain — BOTH flavors. tauri-plugin-extplayer is built for lite and full alike, and its
# dependencies resolve kotlin-stdlib 2.1.20; the scaffolded Kotlin Gradle plugin is older, so
# compiling the plugin against that stdlib fails with "Class 'kotlin.Unit' was compiled with an
# incompatible version of Kotlin" plus a cascade of unresolved references to stdlib members (it,
# use, toByteArray, bufferedReader). This bump used to be inside the full-only branch, which is
# exactly why full built and lite did not.
sed -i -E 's/kotlin-gradle-plugin:[0-9.]+/kotlin-gradle-plugin:2.2.0/' src-tauri/gen/android/build.gradle.kts
grep -q 'kotlin-gradle-plugin:2.2.0' src-tauri/gen/android/build.gradle.kts \
  || { echo "kotlin-gradle-plugin bump missed — scaffold shape changed"; exit 1; }

if [ "$FLAVOR" = "full" ]; then
  # Never let a distributable full APK silently fall back to Maven Central's 0.17.4 AAR. The
  # workflow must stage the reviewed source build before scaffolding; assert both its presence and
  # the libass version embedded in the actual libmpv payload.
  LIBMPV_AAR="src-tauri/tauri-plugin-mpv/android/libs/libmpv.aar"
  test -s "$LIBMPV_AAR" \
    || { echo "secure libmpv AAR missing — run scripts/ci/libmpv-android.sh first"; exit 1; }
  unzip -p "$LIBMPV_AAR" jni/arm64-v8a/libmpv.so \
    | strings | grep 'commit: 0\.17\.5-' >/dev/null \
    || { echo "staged libmpv does not contain libass 0.17.5"; exit 1; }

  # Picture-in-picture is a full-flavor feature: it needs the embedded player. `resizeableActivity`
  # is the other half of the contract — an activity the system treats as non-resizeable is refused
  # entry to PiP on some OEM builds even with the flag above, and the scaffolded manifest never
  # states it. The existing `configChanges` list already covers
  # screenSize|smallestScreenSize|screenLayout, so the window resize into (and back out of) the
  # miniplayer is handled in-process rather than recreating the activity — which would tear down the
  # mpv core mid-playback.
  sed -i 's#android:name=".MainActivity"#android:name=".MainActivity"\n            android:supportsPictureInPicture="true"\n            android:resizeableActivity="true"#' src-tauri/gen/android/app/src/main/AndroidManifest.xml
  grep -q 'android:supportsPictureInPicture="true"' src-tauri/gen/android/app/src/main/AndroidManifest.xml \
    || { echo "picture-in-picture manifest patch missed"; exit 1; }
fi
