#!/usr/bin/env bash
# Scaffold + patch the Android Gradle project for a CI build.
#
# `gen/android` is gitignored and regenerated by `tauri android init`, so every project tweak has
# to be re-applied on each run — it cannot be committed. Shared by the release matrix and the PR
# preview build so the two cannot drift: a patch that lands here is in both, and every patch
# verifies itself rather than silently no-oping when the scaffold template changes.
#
# Usage: scripts/ci/android-scaffold.sh <lite|full>
set -euo pipefail

FLAVOR="${1:?usage: android-scaffold.sh <lite|full>}"
case "$FLAVOR" in
  lite|full) ;;
  *) echo "unknown flavor: $FLAVOR (expected lite or full)"; exit 1 ;;
esac

npx tauri android init

# Android 16 / API 36 is required for Play submissions from 2026-08-31. Pin both generated
# values instead of relying on whichever defaults happen to ship in the installed Tauri CLI.
sed -i -E 's/compileSdk = [0-9]+/compileSdk = 36/' src-tauri/gen/android/app/build.gradle.kts
sed -i -E 's/targetSdk = [0-9]+/targetSdk = 36/' src-tauri/gen/android/app/build.gradle.kts
grep -q 'compileSdk = 36' src-tauri/gen/android/app/build.gradle.kts \
  || { echo "compileSdk 36 patch missed — scaffold shape changed"; exit 1; }
grep -q 'targetSdk = 36' src-tauri/gen/android/app/build.gradle.kts \
  || { echo "targetSdk 36 patch missed — scaffold shape changed"; exit 1; }

# Tauri 2.11's generated WryActivity disables its AndroidX callback, then falls through via the
# deprecated Activity.onBackPressed(). Android 16 no longer calls that method for targetSdk 36.
# Fall through through the dispatcher instead: AndroidX bridges it to OnBackInvokedDispatcher and
# preserves WebView history plus predictive back-to-home when there is no earlier callback.
WRY_ACTIVITY="$(find src-tauri/gen/android/app/src/main/java -name WryActivity.kt -print -quit)"
test -n "$WRY_ACTIVITY" || { echo "generated WryActivity.kt not found"; exit 1; }
sed -i 's/this@WryActivity\.onBackPressed()/this@WryActivity.onBackPressedDispatcher.onBackPressed()/' \
  "$WRY_ACTIVITY"
grep -q 'this@WryActivity.onBackPressedDispatcher.onBackPressed()' "$WRY_ACTIVITY" \
  || { echo "predictive-back patch missed — WryActivity template changed"; exit 1; }

# The generated MainActivity already opts into AndroidX's inset handling. Make a template change
# fail the build rather than silently shipping content under the status/navigation bars.
MAIN_ACTIVITY="$(find src-tauri/gen/android/app/src/main/java -name MainActivity.kt -print -quit)"
test -n "$MAIN_ACTIVITY" || { echo "generated MainActivity.kt not found"; exit 1; }
grep -q 'enableEdgeToEdge()' "$MAIN_ACTIVITY" \
  || { echo "edge-to-edge setup missing from MainActivity"; exit 1; }

# `android init` synthesizes launcher resources from the generic desktop icon and can overwrite the
# hand-tuned adaptive foreground. Install the canonical Izumi Android resources after scaffolding so
# both the APK installer preview and launcher use Izumi, never Tauri's template icon. Also declare
# the dedicated circular legacy asset.
cp -R src-tauri/icons/android/. src-tauri/gen/android/app/src/main/res/
if ! grep -q 'android:roundIcon=' src-tauri/gen/android/app/src/main/AndroidManifest.xml; then
  sed -i 's#android:icon="@mipmap/ic_launcher"#android:icon="@mipmap/ic_launcher"\n        android:roundIcon="@mipmap/ic_launcher_round"#' src-tauri/gen/android/app/src/main/AndroidManifest.xml
fi
cmp src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher.png \
    src-tauri/gen/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
grep -q '#0E1524' src-tauri/gen/android/app/src/main/res/values/ic_launcher_background.xml

# navigator.onLine only reflects real connectivity when the app holds ACCESS_NETWORK_STATE; without
# it the WebView always reports online, so offline mode's launch auto-detect + the offline banner
# never fire on Android. Applies to BOTH flavors (both are WebView apps).
sed -i 's#<uses-permission android:name="android.permission.INTERNET" />#<uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />#' src-tauri/gen/android/app/src/main/AndroidManifest.xml

# Kotlin toolchain — BOTH flavors. tauri-plugin-extplayer is built for lite and full alike, and its
# dependencies resolve kotlin-stdlib 2.1.20; the scaffolded Kotlin Gradle plugin is older, so
# compiling the plugin against that stdlib fails with "Class 'kotlin.Unit' was compiled with an
# incompatible version of Kotlin" plus a cascade of unresolved references to stdlib members (it,
# use, toByteArray, bufferedReader). This bump used to be inside the full-only branch, which is
# exactly why full built and lite did not.
sed -i -E 's/kotlin-gradle-plugin:[0-9.]+/kotlin-gradle-plugin:2.2.0/' src-tauri/gen/android/build.gradle.kts
grep -q 'kotlin-gradle-plugin:2.2.0' src-tauri/gen/android/build.gradle.kts \
  || { echo "kotlin-gradle-plugin bump missed — scaffold shape changed"; exit 1; }

if [ "$FLAVOR" = "full" ]; then
  # Never let a distributable full APK silently fall back to Maven Central's 0.17.4 AAR. The
  # workflow must stage the reviewed source build before scaffolding; assert both its presence and
  # the libass version embedded in the actual libmpv payload.
  LIBMPV_AAR="src-tauri/tauri-plugin-mpv/android/libs/libmpv.aar"
  test -s "$LIBMPV_AAR" \
    || { echo "secure libmpv AAR missing — run scripts/ci/libmpv-android.sh first"; exit 1; }
  unzip -p "$LIBMPV_AAR" jni/arm64-v8a/libmpv.so \
    | strings | grep 'commit: 0\.17\.5-' >/dev/null \
    || { echo "staged libmpv does not contain libass 0.17.5"; exit 1; }

  # Picture-in-picture is a full-flavor feature: it needs the embedded player. `resizeableActivity`
  # is the other half of the contract — an activity the system treats as non-resizeable is refused
  # entry to PiP on some OEM builds even with the flag above, and the scaffolded manifest never
  # states it. The existing `configChanges` list already covers
  # screenSize|smallestScreenSize|screenLayout, so the window resize into (and back out of) the
  # miniplayer is handled in-process rather than recreating the activity — which would tear down the
  # mpv core mid-playback.
  sed -i 's#android:name=".MainActivity"#android:name=".MainActivity"\n            android:supportsPictureInPicture="true"\n            android:resizeableActivity="true"#' src-tauri/gen/android/app/src/main/AndroidManifest.xml
  grep -q 'android:supportsPictureInPicture="true"' src-tauri/gen/android/app/src/main/AndroidManifest.xml \
    || { echo "picture-in-picture manifest patch missed"; exit 1; }
fi
