"$schema" = "schemas/schema.json"

[default]
description = "Allow controlling the embedded libmpv player."
permissions = [
    "allow-mpv-load",
    "allow-mpv-command",
    "allow-mpv-get",
    "allow-mpv-set",
    "allow-mpv-stop",
    "allow-mpv-pip",
    "allow-mpv-viewport",
    "allow-mpv-fullscreen",
    "allow-mpv-transform",
    "allow-mpv-brightness",
    "allow-mpv-haptic",
    "allow-mpv-thumb",
    "allow-mpv-gif-start",
    "allow-mpv-gif-stop",
    "allow-mpv-gif-abort",
    "allow-mpv-gif-save",
    "allow-registerListener",
    "allow-removeListener",
]
