import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(fileURLToPath(new URL(path, import.meta.url)), 'utf8')

describe('DiscussAnime embed theming', () => {
  it('loads the official host-side theme bridge on demand instead of at app startup', () => {
    const layout = read('../../routes/+layout.svelte')
    const loader = read('./embed-theme.ts')
    expect(layout).not.toContain('https://discussanime.moe/embed.js')
    expect(loader.match(/https:\/\/discussanime\.moe\/embed\.js/g)).toHaveLength(1)
    expect(loader).toContain("script.type = 'module'")
    expect(loader).toContain("document.getElementById(SCRIPT_ID)")
  })

  it('does not force dark mode through URLs or iframe styles', () => {
    const panel = read('../components/player/CommentsPanel.svelte')
    const mobile = read('./mobile.ts')
    const android = read('../components/player/AndroidWatchDetails.svelte')

    expect(panel).not.toContain('withDark')
    expect(panel).not.toContain("set('theme', 'dark')")
    expect(mobile).not.toContain("set('theme', 'dark')")
    expect(android).not.toContain('style:color-scheme="dark"')
  })

  it('lets the browser chain an Android drag out of the cross-origin child, and only watches it', () => {
    const loader = read('../../../static/disqus-embed.html')
    const android = read('../components/player/AndroidWatchDetails.svelte')
    const plugin = read('../../../src-tauri/tauri-plugin-extplayer/android/src/main/java/app/izumi/extplayer/ExtPlayerPlugin.kt')

    expect(loader).toMatch(/html\.izumi-expand, html\.izumi-expand body\s*\{[^}]*overflow: hidden;[^}]*overscroll-behavior-y: auto;/s)
    expect(android).toMatch(/title="Episode comments"[^>]*scrolling="no"/)
    expect(android).toContain('style:height={`${disqusHeight}px`}')
    expect(android).not.toContain('min(70dvh')
    expect(android).toContain("closest<HTMLElement>('.preparing-details, .watch-details')")
    expect(android).toContain('embedTouchScroll(event.origin, event.data, window.location.origin)')
    expect(android).toContain('decideEmbedGestureOwner(')
    expect(loader).toContain("type: 'izumi-disqus-page-scroll'")
    expect(loader).toContain('cancelable: message.cancelable !== false')
    // The bridge inside disqus.com must never cancel or swallow a touch: a cancelled touchmove
    // raced the native scroll (double distance on a slow drag, a main-thread fling on a quick one)
    // and made every touch on the comments wait on JavaScript.
    const bridge = plugin.slice(plugin.indexOf('window.__izumiDisqusTouchBridge'), plugin.indexOf('""".trimIndent()'))
    expect(bridge).toContain("type: 'izumi-disqus-touch-scroll'")
    expect(bridge).toContain("document.addEventListener('touchmove'")
    expect(bridge).not.toContain('preventDefault')
    expect(bridge).not.toContain('stopPropagation')
    expect(bridge).not.toContain('passive: false')
    expect(bridge).toContain('event.cancelable')
  })

  it('loads and sizes the current Disqus application on Android', () => {
    const loader = read('../../../static/disqus-embed.html')
    const android = read('../components/player/AndroidWatchDetails.svelte')
    expect(loader).toContain("https://c.disquscdn.com")
    expect(loader).toMatch(/html\.izumi-expand #disqus_thread > iframe\s*\{[^}]*min-height: 480px !important;/s)
    expect(loader).toContain('var heightTimer = 0')
    expect(loader).toContain('heightTimer = window.setTimeout')
    // Content height, never the viewport's: `documentElement.scrollHeight` is at least the frame's
    // own height, so a frame the app had grown could never report a smaller number again.
    expect(loader).not.toContain('document.documentElement.scrollHeight')
    expect(loader).toContain("event.data.type === 'izumi-disqus-request-height'")
    // The reset is keyed on the embed URL string: the discussion object is rebuilt on every
    // threads update, and the second (full) update used to reset a frame that had already grown.
    expect(android).toContain("const disqusSrc = $derived(discussion?.kind === 'disqus' ? discussion.embedSrc : null)")
    expect(android).toContain("postToFrame({ type: 'izumi-disqus-request-height' })")
    expect(android).not.toMatch(/\$effect\(\(\) => \{\s*discussion\?\.kind === 'disqus' \? discussion\.embedSrc : null/)
  })

  it('removes native dark-frame mutation and forced WebView theming', () => {
    const lib = read('../../../src-tauri/src/lib.rs')
    const androidScaffold = read('../../../scripts/ci/android-scaffold.sh')
    expect(lib).not.toContain('DARK_FRAME_SCRIPT')
    expect(lib).not.toContain('COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK')
    expect(lib).not.toContain('.theme(Some(tauri::Theme::Dark))')
    expect(androidScaffold).not.toContain('android:isLightTheme')
    expect(lib).toContain('DISQUS_PROFILE_SCRIPT')
  })

  it('keeps the Deck embed on a download-free font path with touch scroll containment', () => {
    const loader = read('../../../static/disqus-embed.html')
    const lib = read('../../../src-tauri/src/lib.rs')
    const panel = read('../components/player/CommentsPanel.svelte')
    const keyboard = read('../components/shell/OnScreenKeyboard.svelte')
    expect(loader).not.toContain('fonts.googleapis.com')
    expect(loader).not.toContain('fonts.gstatic.com')
    expect(loader).toContain('font-family: system-ui')
    expect(loader).toContain('overscroll-behavior: contain; touch-action: pan-y;')
    expect(loader).toContain("message.type !== 'izumi-disqus-touch-scroll'")
    expect(loader).toContain('window.requestAnimationFrame(flushTouchScroll)')
    expect(loader).toContain("message.phase === 'start'")
    expect(loader).not.toContain('notifyHostMotion')
    expect(lib).toContain('COMMENTS_TOUCH_SCROLL_SCRIPT')
    expect(lib).toContain('UserContentInjectedFrames::AllFrames')
    expect(lib).toContain("host==='theanimecommunity.com'")
    expect(lib).toContain("host==='discussanime.moe'&&path.indexOf('/embed/')===0")
    expect(lib).toContain("relay('start',0,0)")
    expect(lib).toContain('inputKind=null,pointerId=null')
    expect(lib).toContain("attributeFilter:['title']")
    expect(lib).toContain("setAttribute('aria-label',title)")
    expect(lib).toContain('Number.isFinite(t.screenY)?t.screenY:t.clientY')
    expect(lib).toContain('now-lastTouchAt<700')
    expect(lib).toContain('Math.abs(total)<10')
    expect(lib).toContain("isSeeMore(exact)")
    expect(lib).toContain('[contenteditable]:not([contenteditable="false"])')
    expect(lib).toContain('[role="textbox"]')
    expect(lib).toContain('visibleComposer()')
    expect(lib).toContain("tapTarget=interactiveTarget(ev.target)||ev.target;begin")
    expect(lib).toContain('focusComposer(exact,true)')
    expect(lib).toContain('suppressClickUntil=performance.now()+700')
    expect(lib).toContain("type:'izumi-comments-focus-input'")
    expect(lib).toContain("m.type!=='izumi-comments-key'")
    expect(lib).toContain("editComposer(m.action")
    expect(lib).toContain("join\\s+the\\s+discussion")
    expect(lib).not.toContain('open_url("steam://open/keyboard"')
    expect(lib).toContain('steam_osk: unavailable — using HTML fallback')
    expect(panel).toContain("m?.type === 'izumi-comments-focus-input'")
    expect(panel).toContain("invoke<boolean>('steam_show_osk'")
    expect(panel).toContain('disqus-composer: keyboard requested')
    expect(panel).toContain("new CustomEvent('osk-remote-open'")
    expect(panel).toContain("type: 'izumi-comments-key'")
    expect(panel).toContain('$fullscreen && !$isAndroid')
    expect(keyboard).toContain("window.addEventListener('osk-remote-open'")
    expect(keyboard).toContain('remote.insert(ch)')
    expect(panel).toContain("m?.type === 'izumi-comments-touch-scroll'")
    expect(panel).not.toContain('izumi-comments-scroll-activity')
    expect(panel).not.toContain('commentsOverlayMoving')
    expect(panel).toContain("phase === 'start'")
    expect(panel).toContain("$gameMode ? 'inset-0 h-full w-full max-w-none border-0 shadow-none'")
    expect(panel).toContain('class:animate-pulse={!$gameMode}')
    expect(panel).toContain("'inset-0 h-full w-full max-w-none border-0 shadow-none'")
  })
})
