<script lang="ts">
  import type { Media } from '$lib/anilist/types'
  import { banner, cover, title, format, status, season, totalEpisodes } from '$lib/anilist/media'
  import { rememberDetail } from '$lib/anilist/detail-hint'
  import Play from '@lucide/svelte/icons/play'
  import Info from '@lucide/svelte/icons/info'
  import Heart from '@lucide/svelte/icons/heart'
  import Clock3 from '@lucide/svelte/icons/clock-3'
  import ChevronLeft from '@lucide/svelte/icons/chevron-left'
  import ChevronRight from '@lucide/svelte/icons/chevron-right'
  import * as h from '$lib/haptics'
  import { isAndroid, isMobile } from '$lib/platform'
  import { get } from 'svelte/store'
  import { gameMode, playing } from '$lib/player/session'
  import { androidMpvActive } from '$lib/player/android-mpv'
  import { airingCountdown } from '$lib/anime/airing-labels'
  import { dragCarousels, wheelScrollAcross } from '$lib/settings/ui'
  import { untrack } from 'svelte'

  // Bottom-left content column + clean linear scrims. Discovery facts stay deliberately compact:
  // format/runtime/production/score, then one context line for next-airing + genres. Detail pages
  // pass one media with showOverlay=false (backdrop only).
  let {
    medias,
    onplay,
    oninfo,
    onfav,
    showOverlay = true,
    initialArtworkVisible = false,
  }: {
    medias: Media[]
    onplay?: (m: Media) => void
    oninfo?: (m: Media) => void
    onfav?: (m: Media) => void
    showOverlay?: boolean
    /** The detail skeleton already painted this exact banner; settle it without replaying a slide. */
    initialArtworkVisible?: boolean
  } = $props()

  let i = $state(0)
  let loadedArtworkId = $state<number | null>(untrack(() => initialArtworkVisible ? (medias[0]?.id ?? null) : null))
  let cycle = $state(0)
  let scrolled = $state(false)
  let navDirection = $state<1 | -1>(1)
  let clock = $state(Date.now())
  let countdownOrigin = $state(Date.now())
  let failedLogos = $state<string[]>([])
  const DURATION = 15000 // a 15s cadence

  function go(n: number, direction?: 1 | -1) {
    if (n === i) return
    navDirection = direction ?? (n > i ? 1 : -1)
    i = n
    cycle += 1
  }

  function step(direction: 1 | -1) {
    const n = medias.length
    if (n > 1) go((i + direction + n) % n, direction)
  }

  // Swipe left/right to change the featured slide (only when there's more than one). `touch-pan-y`
  // on the container lets the browser own vertical scroll while horizontal swipes reach here.
  let touchX = 0
  let swiped = false
  let swipeResetFrame = 0
  function onTouchStart(e: TouchEvent) {
    touchX = e.touches[0].clientX
    swiped = false
    cancelAnimationFrame(swipeResetFrame)
  }
  function onTouchEnd(e: TouchEvent) {
    const n = medias.length
    if (n < 2) return
    const dx = e.changedTouches[0].clientX - touchX
    if (Math.abs(dx) < 40) return
    swiped = true
    // Suppress only the synthetic click generated by this swipe. Some WebViews omit that click;
    // leaving a boolean armed until the next real tap made the newly-arrived slide feel disabled.
    swipeResetFrame = requestAnimationFrame(() => (swiped = false))
    h.tap()
    step(dx < 0 ? 1 : -1)
  }

  // Desktop counterpart to touch swiping. It is intentionally release-to-step rather than a
  // continuously moving DOM tree: the banner, scrims and controls remain compositor-stable while
  // held, then the existing directional entrance animation performs the previous/next transition.
  let heroPointer: number | null = null
  let heroDragX = 0
  let heroDragging = $state(false)
  function onHeroPointerDown(e: PointerEvent) {
    if (!$dragCarousels || e.pointerType !== 'mouse' || e.button !== 0 || medias.length < 2) return
    if ((e.target as HTMLElement | null)?.closest('button, a, input, select, textarea')) return
    heroPointer = e.pointerId
    heroDragX = e.clientX
    heroDragging = false
  }
  function onHeroPointerMove(e: PointerEvent) {
    if (heroPointer !== e.pointerId) return
    if (Math.abs(e.clientX - heroDragX) <= 5) return
    heroDragging = true
    try { (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId) } catch { /* optional */ }
    e.preventDefault()
  }
  function endHeroPointer(e: PointerEvent, navigate: boolean) {
    if (heroPointer !== e.pointerId) return
    const dx = e.clientX - heroDragX
    heroPointer = null
    try { (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId) } catch { /* optional */ }
    const didDrag = heroDragging
    heroDragging = false
    if (navigate && didDrag && Math.abs(dx) >= 48) {
      h.tap()
      step(dx < 0 ? 1 : -1)
    }
  }

  // A trackpad emits a burst of wheel events plus momentum for one two-finger swipe. Accumulate the
  // small opening deltas and step once. A fresh swipe can begin before macOS momentum has gone fully
  // quiet, so also re-arm when its new acceleration is clearly larger than the decaying tail.
  let heroWheelTotal = 0
  let heroWheelStepped = false
  let heroWheelSteppedAt = 0
  let heroWheelLastMagnitude = 0
  let heroWheelReset: ReturnType<typeof setTimeout> | undefined
  function onHeroWheel(e: WheelEvent) {
    if (!$wheelScrollAcross || medias.length < 2 || Math.abs(e.deltaX) <= Math.abs(e.deltaY)) return
    e.preventDefault()
    const now = performance.now()
    const magnitude = Math.abs(e.deltaX)
    clearTimeout(heroWheelReset)
    heroWheelReset = setTimeout(() => {
      heroWheelTotal = 0
      heroWheelStepped = false
      heroWheelSteppedAt = 0
      heroWheelLastMagnitude = 0
    }, 180)
    if (heroWheelStepped) {
      const freshGesture = now - heroWheelSteppedAt > 160
        && magnitude >= Math.max(10, heroWheelLastMagnitude * 1.8)
      heroWheelLastMagnitude = magnitude
      if (!freshGesture) return
      heroWheelTotal = 0
      heroWheelStepped = false
    } else {
      heroWheelLastMagnitude = magnitude
    }
    heroWheelTotal += e.deltaX
    if (Math.abs(heroWheelTotal) < 24) return
    heroWheelStepped = true
    heroWheelSteppedAt = now
    h.tap()
    step(heroWheelTotal < 0 ? -1 : 1)
  }

  function openCurrent() {
    // A horizontal swipe ends with a synthetic click on some Android WebViews. Consume it so
    // changing slides never also opens the title underneath the finger.
    if (swiped) { swiped = false; return }
    h.tap()
    rememberDetail(current)
    oninfo?.(current)
  }

  // Auto-advance + scroll fade, only when there's an overlay (Home).
  $effect(() => {
    const n = medias.length
    if (!n || !showOverlay) return
    // Track manual navigation too: changing `cycle` tears down/re-arms this one-shot timer and
    // restarts the compositor-only progress animation below.
    void cycle
    let timer: ReturnType<typeof setTimeout> | undefined
    // The home route is HIDDEN, not unmounted, while the player is up (see app/+layout.svelte's
    // `class:hidden={$playing || $androidMpvActive}`). Do not advance underneath mpv; restart a full
    // interval when the home page becomes visible again.
    const stalled = () => document.hidden || get(playing) || get(androidMpvActive)
    const arm = () => {
      if (timer) clearTimeout(timer)
      timer = undefined
      if (!stalled()) timer = setTimeout(() => step(1), DURATION)
    }
    arm()
    const onWake = () => arm()
    document.addEventListener('visibilitychange', onWake)
    const stopPlaying = playing.subscribe(onWake)
    const stopAndroidMpv = androidMpvActive.subscribe(onWake)
    const onScroll = () => (scrolled = (window.scrollY ?? 0) > 100)
    window.addEventListener('scroll', onScroll)
    // Steam Deck: L1/R1 step through the featured banners (dispatched by the gamepad translator
    // while on the home screen). detail = -1 (prev) / +1 (next); wraps.
    const onHeroNav = (e: Event) => step((e as CustomEvent<number>).detail < 0 ? -1 : 1)
    window.addEventListener('hero-nav', onHeroNav)
    return () => {
      if (timer) clearTimeout(timer)
      cancelAnimationFrame(swipeResetFrame)
      clearTimeout(heroWheelReset)
      document.removeEventListener('visibilitychange', onWake)
      stopPlaying()
      stopAndroidMpv()
      window.removeEventListener('scroll', onScroll)
      window.removeEventListener('hero-nav', onHeroNav)
    }
  })

  // Countdown targets are absolute in current AniList responses. Keep a response-time fallback for
  // an older cached object that only has timeUntilAiring, and update the compact badge once a second.
  $effect(() => {
    void medias
    countdownOrigin = Date.now()
  })
  $effect(() => {
    if (!showOverlay) return
    const timer = setInterval(() => (clock = Date.now()), 1_000)
    return () => clearInterval(timer)
  })

  const current = $derived(medias[Math.min(i, Math.max(0, medias.length - 1))])
  const currentLogo = $derived(current?.logoImage && !failedLogos.includes(current.logoImage) ? current.logoImage : '')
  function logoFailed(event: Event) {
    const src = (event.currentTarget as HTMLImageElement).src
    if (!failedLogos.includes(src)) failedLogos = [...failedLogos, src]
  }
  const artworkReady = $derived(loadedArtworkId === current?.id)
  const artworkSettled = () => (loadedArtworkId = current.id)
  // Accent: tint everything off the cover's dominant color; theme fallback.
  const accent = $derived(current?.coverImage?.color || 'hsl(346.6 79.12% 51.18%)')
  const nextAiring = $derived(current?.nextAiringEpisode)
  const nextAiringAt = $derived(
    nextAiring?.airingAt ?? (nextAiring ? countdownOrigin / 1000 + nextAiring.timeUntilAiring : 0),
  )
  const nextAiringLabel = $derived(
    nextAiring?.episode && nextAiringAt
      ? `Episode ${nextAiring.episode} in ${airingCountdown(nextAiringAt, clock)}`
      : '',
  )
  const productionLabel = $derived(current?.studios?.nodes?.[0]?.name || season(current))
  const scoreColor = (s?: number) =>
    s == null ? 'text-white/70' : s >= 75 ? 'text-green-400' : s >= 65 ? 'text-orange-400' : 'text-red-400'
  const cleanDesc = (d?: string) => (d ?? '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim()
</script>

{#if current}
  {#if $isMobile && showOverlay}
    <!-- Mobile Home: a CONTAINED poster block (not a full-bleed banner) — reads far better on a
         phone (Netflix-style). Portrait cover art, dark bottom scrim, title/meta/genres + Watch,
         swipeable with dot pips. -->
    <!-- Height in vh (not a portrait aspect ratio): stays bounded + usable in landscape, where a
         3/4 aspect on a wide viewport overflowed the screen. A touch smaller than before. -->
    <div
      class="relative mx-4 mb-6 h-[46vh] touch-pan-y overflow-hidden rounded-2xl shadow-xl {$isAndroid ? 'android-hero-press' : ''}"
      style="--accent:{accent}"
      role="group"
      aria-label="Featured"
      ontouchstart={onTouchStart}
      ontouchend={onTouchEnd}
    >
      {#key current.id}
        <div class="hero-slide-in absolute inset-0" style="--hero-enter-x:{navDirection * 3}%">
          {#if !artworkReady}<div class="absolute inset-0 skeloader"></div>{/if}
          <img src={cover(current)} alt="" draggable="false" loading="eager" decoding="async" fetchpriority="high"
               onload={artworkSettled} onerror={artworkSettled}
               class="relative h-full w-full object-cover transition-opacity duration-200 {artworkReady ? 'opacity-100' : 'opacity-0'}" />
        </div>
      {/key}
      <div class="absolute inset-0 bg-gradient-to-t from-black/95 via-black/25 to-transparent"></div>
      {#if $isAndroid && oninfo}
        <!-- Whole-card Android hit target. It sits above the artwork but below the explicit
             actions, so Watch/Details/pips retain their own behaviour. -->
        <button type="button" data-focusable class="android-hero-hit absolute inset-0 z-10"
                onclick={openCurrent} aria-label={`View details for ${title(current)}`}></button>
      {/if}
      <div class="pointer-events-none absolute inset-x-0 bottom-0 z-20 flex flex-col gap-2 p-4">
        {#if currentLogo}
          <h1 aria-label={title(current)} class="h-16 w-[82%]">
            <img src={currentLogo} alt="" loading="eager" decoding="async"
                 onerror={logoFailed}
                 class="h-full w-full object-contain object-left drop-shadow-[2px_2px_5px_rgba(0,0,0,.9)]" />
          </h1>
        {:else}
          <h1 class="line-clamp-2 text-2xl font-black leading-tight text-white drop-shadow-[2px_2px_4px_rgba(0,0,0,.9)]">{title(current)}</h1>
        {/if}
        <div class="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs font-semibold text-white/90
                    [&>span:not(:first-child)]:before:mr-2 [&>span:not(:first-child)]:before:text-white/40 [&>span:not(:first-child)]:before:content-['•']">
          {#if format(current)}<span>{format(current)}</span>{/if}
          {#if totalEpisodes(current) > 1}<span>{totalEpisodes(current)} eps</span>{/if}
          {#if current.duration}<span>{current.duration} min</span>{/if}
          {#if current.averageScore}<span class={scoreColor(current.averageScore)}>{current.averageScore}% score</span>{/if}
          {#if !nextAiringLabel && status(current)}<span>{status(current)}</span>{/if}
        </div>
        {#if nextAiringLabel || current.genres?.length}
          <div class="flex flex-wrap items-center gap-1.5">
            {#if nextAiringLabel}
              <span class="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-black/55 px-2.5 py-1 text-[0.7rem] font-black text-white shadow-lg backdrop-blur">
                <Clock3 size={12} />{nextAiringLabel}
              </span>
            {/if}
            {#each current.genres?.slice(0, 3) ?? [] as g (g)}
              <span class="rounded-full border border-white/10 bg-white/15 px-2.5 py-0.5 text-[0.7rem] font-bold text-white/90">{g}</span>
            {/each}
          </div>
        {/if}
        <div class="mt-1 flex items-center gap-2">
          <button data-focusable onclick={() => { rememberDetail(current); onplay?.(current) }}
                  class="pointer-events-auto flex flex-1 items-center justify-center gap-2 rounded-lg py-2.5 font-bold text-black shadow-lg"
                  style="background:var(--accent)">
            <Play size={18} fill="currentColor" /> Watch
          </button>
          <button data-focusable onclick={() => { rememberDetail(current); oninfo?.(current) }}
                  class="pointer-events-auto flex items-center gap-2 rounded-lg bg-white/15 px-4 py-2.5 font-bold text-white backdrop-blur">
            <Info size={18} /> Details
          </button>
        </div>
        {#if medias.length > 1}
          <div class="mt-1.5 flex justify-center gap-1.5">
            {#each medias as _, idx (idx)}
              <button type="button" onclick={() => go(idx)} aria-label={`Slide ${idx + 1}`}
                      class="pointer-events-auto h-1.5 rounded-full transition-all duration-300 {idx === i ? 'w-5 bg-white' : 'w-1.5 bg-white/40'}"></button>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  {:else}
  <div
    data-nav-row
    class="relative mb-6 h-[40vh] touch-pan-y select-none transition-opacity duration-500 {showOverlay ? 'sm:h-[50vh]' : $gameMode ? 'sm:h-[42vh]' : 'sm:h-[48vh]'} {scrolled ? 'opacity-40' : 'opacity-100'}"
    class:cursor-grab={$dragCarousels && medias.length > 1}
    class:cursor-grabbing={heroDragging}
    class:game-home-hero={$gameMode && showOverlay}
    style="--accent:{accent}"
    role="group"
    aria-label="Featured"
    ontouchstart={onTouchStart}
    ontouchend={onTouchEnd}
    onpointerdown={onHeroPointerDown}
    onpointermove={onHeroPointerMove}
    onpointerup={(e) => endHeroPointer(e, true)}
    onpointercancel={(e) => endHeroPointer(e, false)}
    onwheel={onHeroWheel}
  >
    <!-- Full-bleed banner: on desktop it breaks out of main's left margin (behind the
         sidebar) and up under the frameless titlebar. On mobile there's no sidebar/titlebar,
         so anchor it flush to the viewport edge (left-0/top-0) — the desktop -left-14 would
         otherwise leave a black band on the right. Keyed for a crossfade. -->
    <div class="pointer-events-none absolute left-0 top-0 h-[calc(100%+2rem)] w-screen overflow-hidden sm:-left-14 sm:-top-8">
      {#key current.id}
        <div class="{initialArtworkVisible && !showOverlay ? 'detail-hero-reveal' : 'hero-slide-in'} absolute inset-0" style="--hero-enter-x:{navDirection * 3}%;--hero-final-opacity:.7">
          {#if !artworkReady}<div class="absolute inset-0 skeloader"></div>{/if}
          <img src={banner(current)} alt="" draggable="false" loading="eager" decoding="async" fetchpriority="high"
               onload={artworkSettled} onerror={artworkSettled}
               class="relative h-full w-full object-cover transition-opacity duration-200 {artworkReady ? 'opacity-100' : 'opacity-0'}"
               style="object-position:center 20%" />
        </div>
      {/key}
      <!-- Dual linear scrims: bright top-right, dark bottom-left. -->
      <div class="absolute inset-0 bg-gradient-to-t from-background via-background/40 to-transparent"></div>
      <div class="absolute inset-y-0 left-0 w-[45%] bg-gradient-to-r from-background/85 via-background/40 to-transparent"></div>
    </div>

    {#if showOverlay && medias.length > 1}
      <!-- Miruro-style edge navigation: entering an edge reveals the control, while an explicit
           click changes the slide. Hover alone never replaces what the viewer was reading. -->
      <button type="button" data-focusable={$gameMode ? undefined : ''} tabindex={$gameMode ? -1 : undefined}
              aria-label="Previous featured title" onclick={() => step(-1)}
              class="hero-edge group absolute left-0 top-1/2 z-20 hidden h-28 w-16 -translate-y-1/2 place-items-center sm:grid">
        <span class="grid size-10 -translate-x-2 place-items-center rounded-full border border-white/15 bg-black/65 text-white opacity-0 shadow-xl backdrop-blur transition-all duration-150 group-hover:translate-x-0 group-hover:opacity-100 group-focus-visible:translate-x-0 group-focus-visible:opacity-100">
          <ChevronLeft size={23} />
        </span>
      </button>
      <button type="button" data-focusable={$gameMode ? undefined : ''} tabindex={$gameMode ? -1 : undefined}
              aria-label="Next featured title" onclick={() => step(1)}
              class="hero-edge group absolute right-0 top-1/2 z-20 hidden h-28 w-16 -translate-y-1/2 place-items-center sm:grid">
        <span class="grid size-10 translate-x-2 place-items-center rounded-full border border-white/15 bg-black/65 text-white opacity-0 shadow-xl backdrop-blur transition-all duration-150 group-hover:translate-x-0 group-hover:opacity-100 group-focus-visible:translate-x-0 group-focus-visible:opacity-100">
          <ChevronRight size={23} />
        </span>
      </button>
    {/if}

    {#if showOverlay}
      <div class="absolute inset-x-0 bottom-0 flex flex-col gap-3 px-4 pb-6 sm:px-8 sm:pb-8">
        {#key current.id}
        <div class="hero-copy max-w-2xl" style="--hero-enter-x:{navDirection * 1.5}%">
          {#if currentLogo}
            <h1 aria-label={title(current)} class="h-24 w-[min(34rem,70vw)]">
              <img src={currentLogo} alt="" loading="eager" decoding="async"
                   onerror={logoFailed}
                   class="h-full w-full object-contain object-left drop-shadow-[2px_2px_6px_rgba(0,0,0,.9)]" />
            </h1>
          {:else}
            <h1 class="truncate text-2xl font-black text-white drop-shadow-[2px_2px_4px_rgba(0,0,0,.9)] sm:text-4xl">{title(current)}</h1>
          {/if}

          <!-- High-signal discovery facts only. Airing context and genres share the next line. -->
          <div class="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm font-semibold text-white/90
                      [&>span:not(:first-child)]:before:mr-2 [&>span:not(:first-child)]:before:text-white/40 [&>span:not(:first-child)]:before:content-['•']">
            {#if format(current)}<span>{format(current)}</span>{/if}
            {#if totalEpisodes(current) > 1}<span>{totalEpisodes(current)} episodes</span>{/if}
            {#if current.duration}<span>{current.duration} min</span>{/if}
            {#if productionLabel}<span>{productionLabel}</span>{/if}
            {#if current.averageScore}<span class={scoreColor(current.averageScore)}>{current.averageScore}% score</span>{/if}
            {#if !nextAiringLabel && status(current)}<span>{status(current)}</span>{/if}
          </div>

          {#if nextAiringLabel || current.genres?.length}
            <div class="mt-3 flex flex-wrap items-center gap-2">
              {#if nextAiringLabel}
                <span class="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-black/50 px-3 py-1.5 text-xs font-black text-white shadow-lg backdrop-blur">
                  <Clock3 size={14} />{nextAiringLabel}
                </span>
              {/if}
              {#each current.genres?.slice(0, 3) ?? [] as g}
                <span class="rounded-full border border-white/10 bg-white/15 px-3 py-1 text-xs font-bold text-white/90 shadow-sm">{g}</span>
              {/each}
            </div>
          {/if}

          {#if current.description}
            <p class="mt-3 line-clamp-2 max-w-xl text-sm text-white/70 drop-shadow sm:line-clamp-3">{cleanDesc(current.description)}</p>
          {/if}

          <div data-nav-row-items class="mt-4 flex items-center gap-2">
            <button data-focusable data-nav-row-default data-nav-scroll-top onclick={() => { rememberDetail(current); onplay?.(current) }}
                    class="flex items-center gap-2 rounded-md px-5 py-2 font-bold text-black shadow-lg transition-transform hover:scale-105"
                    style="background:var(--accent)">
              <Play size={18} fill="currentColor" /> Watch Now
            </button>
            <button data-focusable onclick={() => { rememberDetail(current); oninfo?.(current) }}
                    class="flex items-center gap-2 rounded-md bg-white/10 px-4 py-2 font-bold text-white backdrop-blur transition-colors hover:bg-white/20">
              <Info size={18} /> Details
            </button>
            {#if onfav}
              <button data-focusable onclick={() => onfav?.(current)} aria-label="Favorite"
                      class="rounded-md bg-white/10 p-2.5 text-white backdrop-blur transition-colors hover:bg-white/20">
                <Heart size={18} fill={current.isFavourite ? 'currentColor' : 'transparent'}
                       style={current.isFavourite ? 'color:var(--accent)' : ''} />
              </button>
            {/if}
          </div>
        </div>
        {/key}

        {#if medias.length > 1}
          <!-- Slide pips: hover/click targets are a desktop affordance; on mobile the row
               auto-advances (and would collide with the Watch/Details buttons), so hide them. -->
          <div class="absolute bottom-8 right-8 hidden gap-1.5 sm:flex">
            {#each medias as _, idx}
              <button data-focusable={$gameMode ? undefined : ''} tabindex={$gameMode ? -1 : undefined}
                      onclick={() => go(idx)} aria-label={`Slide ${idx + 1}`}
                      class="h-1 overflow-hidden rounded-full bg-white/25 transition-all duration-700"
                      style="width:{idx === i ? '3rem' : '1.5rem'}">
                {#if idx === i}
                  {#key cycle}
                    <div class="hero-progress h-full" style="background:var(--accent)"></div>
                  {/key}
                {:else}
                  <div class="h-full origin-left" style="transform:scaleX({idx < i ? 1 : 0});background:var(--accent)"></div>
                {/if}
              </button>
            {/each}
          </div>
        {/if}
      </div>
    {/if}
  </div>
  {/if}
{/if}

<style>
  @keyframes hero-progress-fill {
    from { transform: scaleX(0); }
    to { transform: scaleX(1); }
  }
  .hero-progress {
    width: 100%;
    transform-origin: left;
    animation: hero-progress-fill 15s linear forwards;
  }
  @keyframes hero-slide-in {
    from { opacity: 0; transform: translate3d(var(--hero-enter-x), 0, 0) scale(1.015); }
    to { opacity: var(--hero-final-opacity, 1); transform: translate3d(0, 0, 0) scale(1); }
  }
  @keyframes hero-copy-in {
    from { opacity: 0; transform: translate3d(var(--hero-enter-x), 8px, 0); }
    to { opacity: 1; transform: translate3d(0, 0, 0); }
  }
  .hero-slide-in { animation: hero-slide-in 480ms cubic-bezier(.22, 1, .36, 1) both; }
  @keyframes detail-hero-reveal {
    from { opacity: .5; }
    to { opacity: var(--hero-final-opacity, .7); }
  }
  .detail-hero-reveal { animation: detail-hero-reveal 220ms ease-out both; }
  .hero-copy { animation: hero-copy-in 360ms cubic-bezier(.22, 1, .36, 1) both; }
  @media (min-width: 640px) {
    .game-home-hero { height: 54vh; }
  }
  :global(html[data-motion='reduced']) .hero-slide-in,
  :global(html[data-motion='reduced']) .detail-hero-reveal,
  :global(html[data-motion='reduced']) .hero-copy { animation-duration: 1ms; }
</style>
