import { describe, it, expect } from 'vitest'
import { unpack, isPacked } from './jsunpacker'

// The packer's OWN decoder, verbatim — the function body that ships inside every packed script.
// Used as an independent oracle: our arithmetic decoder must agree with the reference
// implementation. (Run here on inputs this test constructs, never on fetched content.)
function referenceDecode(p: string, a: number, c: number, k: string[]): string {
  let e: (c: number) => string
  const d: Record<string, string> = {}
  e = function (c: number): string {
    return (c < a ? '' : e(Math.floor(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36))
  }
  while (c--) d[e(c)] = k[c] || e(c)
  let out = p
  let i = k.length
  while (i--) if (k[i]) out = out.replace(new RegExp('\\b' + e(i) + '\\b', 'g'), k[i])
  return out
}

/** Minimal P.A.C.K.E.R. encoder, so tests can build packed input independently of the decoder. */
function pack(source: string, base = 62): { packed: string; payload: string; count: number; dict: string[] } {
  const words = Array.from(new Set(source.match(/\b\w+\b/g) ?? []))
  const symbol = (n: number): string => {
    const digit = (c: number) => (c > 35 ? String.fromCharCode(c + 29) : c.toString(36))
    return (n < base ? '' : symbol(Math.floor(n / base))) + digit(n % base)
  }
  let payload = source
  words.forEach((w, i) => { payload = payload.replace(new RegExp(`\\b${w}\\b`, 'g'), symbol(i)) })
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  const packed = `eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('${esc(payload)}',${base},${words.length},'${esc(words.join('|'))}'.split('|'),0,{}))`
  return { packed, payload, count: words.length, dict: words }
}

describe('isPacked', () => {
  it('detects a packed block and ignores ordinary source', () => {
    expect(isPacked(pack('function a(){return 1}').packed)).toBe(true)
    expect(isPacked('var sources = [{file:"https://x/v.m3u8"}]')).toBe(false)
  })
})

describe('unpack', () => {
  it('decodes the canonical published test vector', () => {
    // Widely-published P.A.C.K.E.R. sample — third-party fixture, not generated by this test.
    const packed =
      "eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('0 1(){2 3(\"4!\")}',5,5,'function|hello|return|alert|world'.split('|'),0,{}))"
    expect(unpack(packed)).toBe('function hello(){return alert("world!")}')
  })

  it('agrees with the packer\'s own reference decoder', () => {
    const source = 'var sources=[{file:"https://cdn.example/hls/master.m3u8",label:"1080p"}];'
    const { packed, payload, count, dict } = pack(source)
    expect(unpack(packed)).toBe(referenceDecode(payload, 62, count, dict))
    expect(unpack(packed)).toBe(source)
  })

  it('survives payloads containing spaces, backslashes and quotes', () => {
    // The escaping trap: naive chained `.replace` unescaping turns literal spaces into backslashes.
    const source = 'var x = "a b c"; var re = /\\d+\\s/; var q = \'it\\\'s\';'
    expect(unpack(pack(source).packed)).toBe(source)
  })

  it('handles dictionaries larger than the base (multi-character symbols)', () => {
    // >62 distinct words forces two-character symbols, where substitution order matters:
    // replacing `a` before `aa` would corrupt the longer symbol.
    const words = Array.from({ length: 80 }, (_, i) => `word${i}`)
    const source = `${words.join(' + ')};`
    expect(unpack(pack(source).packed)).toBe(source)
  })

  it('resolves a block whose payload is itself a packed block', () => {
    // Real nesting: decoding the outer block yields source that still contains a packed block.
    // The outer wrapper is hand-built with an EMPTY dictionary (count 0) so it is a pure carrier —
    // re-running the toy encoder over already-packed text would rewrite its numeric literals.
    const source = 'var file="https://cdn.example/v.mp4";'
    const inner = pack(source).packed
    const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
    const outer = `eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('${esc(inner)}',62,0,''.split('|'),0,{}))`
    expect(unpack(outer)).toBe(source)
  })

  it('leaves unpacked source and malformed blocks untouched', () => {
    const plain = 'var sources = [{file:"https://x/v.m3u8"}]'
    expect(unpack(plain)).toBe(plain)
    const broken = 'eval(function(p,a,c,k,e,d){garbage))'
    expect(unpack(broken)).toBe(broken)
  })

  it('extracts a real-shaped player config end to end', () => {
    const source = 'jwplayer("player").setup({sources:[{file:"https://s1.example/hls/x/index.m3u8",type:"hls"}],tracks:[{file:"https://s1.example/sub/en.vtt",kind:"captions",label:"English"}]});'
    const out = unpack(pack(source).packed)
    expect(out).toContain('https://s1.example/hls/x/index.m3u8')
    expect(out).toContain('https://s1.example/sub/en.vtt')
  })
})
