import { expect, it } from 'vitest'
import { isSupplementalVideo, isTvVideoCompatible } from './playback-suitability'
it('rejects promotional releases while preserving titles that contain the same words', () => {
  for (const extra of ['Trailer', 'Prologue', 'Featurette', 'Sample']) expect(isSupplementalVideo({ title: `Example Film ${extra} 2160p` }, 'Example Film')).toBe(true)
  expect(isSupplementalVideo({ title: 'The Prologue 2024 1080p' }, 'The Prologue')).toBe(false)
  expect(isSupplementalVideo({ url: 'https://media.example/opaque' }, 'Example Film')).toBe(false)
})
it('retains compatible fallback encodes and rejects declared unsupported variants', () => {
  expect(isSupplementalVideo({ title: 'Example 1080p\nOfficial Prologue' }, 'Example')).toBe(true)
  expect(isSupplementalVideo({ title: 'Example', url: 'https://media.example/Example%20Trailer.mkv' }, 'Example')).toBe(true)
  expect(isSupplementalVideo({ title: 'Example', url: 'https://media.example/opaque?token=preview' }, 'Example')).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 1080p HEVC 12-bit' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 1080p H264 4:4:4' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 2160p DV HEVC' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 2160p DV HDR10 HEVC' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example 1080p H.264 10-bit' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 1080p HEVC 10-bit' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example 1080p AV1' }, { av1: false })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 2160p HDR10' }, { hdr: false })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example 1080p H.264' }, { uhd: false, hdr: false })).toBe(true)
})
it('rejects making-of documentaries indexed under the film', () => {
  expect(isSupplementalVideo({ title: 'Example Film (2026) the Making of an Epic' }, 'Example.Film')).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example 2160p Dolby Vision HDR ENG mp4' })).toBe(false)
})
it('rejects releases whose only declared audio the TV platform cannot decode', () => {
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p BluRay x264 DTS-GROUP' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 2160p BluRay TrueHD Atmos 7.1 HEVC' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p BluRay DTS-HD MA 5.1 x264' })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p BluRay DTS AC3 x264' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p WEB-DL DDP5.1 x264' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example Film 2026 1080p HDTS x265 AAC' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p WEB Opus x264' }, { opus: false })).toBe(false)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p WEB Opus x264' })).toBe(true)
  expect(isTvVideoCompatible({ title: 'Example Film 2016 1080p WEB FLAC x264' }, { flac: false })).toBe(false)
})
it('recognises trailer and teaser labels written in other scripts', () => {
  expect(isSupplementalVideo({ title: 'Пример / Example Film [2026, ProRes encode, DTS-HD MA/AC-3 5.1 ENG] Трейлер #2 (4K/IMAX4K)' }, 'Example Film')).toBe(true)
  expect(isSupplementalVideo({ title: 'Example Film 2026 Tráiler oficial 1080p' }, 'Example Film')).toBe(true)
  expect(isSupplementalVideo({ title: 'Example Film 2026 1080p', behaviorHints: { filename: 'ExampleFilm_IMAX_TLR-2_3840x2024.mkv' } }, 'Example Film')).toBe(true)
  expect(isSupplementalVideo({ title: 'Пример / Example Film [2026, WEB-DL 1080p]' }, 'Example Film')).toBe(false)
})
